package com.soma.wes.admin.audit.domain

enum class AdminAuditTargetType {
    AUTHENTICATION,
    ADMIN_ACCOUNT,
    USER,
    WORKSPACE,
    STUDIO,
    GALLERY,
    PHOTO,
    CONCEPT_FOLDER,
    DETAIL_FOLDER,
    PHOTO_CATEGORY_ASSIGNMENT,
    CATEGORIZATION_JOB,
    PHOTO_RATING,
    SELECTION,
    COLLABORATION,
    ALBUM,
    RETOUCH_REQUEST,
    SYSTEM_SETTING,
    TRASH_BATCH,
    IMPERSONATION,
    ADMIN_OPERATION,
}
