package com.soma.wes.admin.audit.domain

enum class AdminAuditAction {
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    LOGOUT,
    PASSWORD_CHANGED,
    ACCOUNT_CREATED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_ACTIVATED,
    ACCOUNT_UNLOCKED,
    TEMPORARY_PASSWORD_ISSUED,
    CLI_RECOVERY,
    REVISION_RESTORED,
    ORIGINAL_PHOTO_VIEWED,
    ORIGINAL_PHOTO_DOWNLOADED,
    READ_ONLY_IMPERSONATION_VIEWED,
}
