-- 하객 협업 세션. 로그인하지 않는 하객·부모님이 링크로 들어와 사진에 의견을 남긴다.
--
-- gallery_members에 얹지 않은 이유는 user_id가 NOT NULL이기 때문이다. 계정이 없는 사람은
-- 멤버 행 자체를 만들 수 없어서, 하객 참여는 멤버십이 아니라 갤러리에 붙는 능력으로 다룬다.
--
-- 갤러리당 여러 개다. 부부는 묶음마다 물어볼 상대가 다르다 — 본식 후보는 부모님께, 2부 사진은
-- 친구들에게. 세션이 하나뿐이면 그 둘을 한 링크에 섞어 보내야 하고, 그러면 받은 의견도 누구에게
-- 무엇을 물어서 나온 것인지 갈라지지 않는다. 그래서 gallery_id는 유니크가 아니라 인덱스다.
--
-- 대신 이름을 받는다(name). 링크가 여러 개인 순간 "어느 링크였더라"가 곧바로 생기고, 토큰은
-- 사람이 알아볼 수 있는 값이 아니다.
--
-- 어느 링크로 들어왔는지는 share_token이 혼자 답한다. 그래서 하객이 부르는 경로는 갤러리를
-- 알 필요가 없고, 한 링크로는 그 세션에 담긴 사진만 보인다(collab_photos가 세션에 매달려 있다).
--
-- 링크가 퍼졌을 때는 세션을 새로 만드는 것이 아니라 revoked_at을 세우고 share_token만 새로
-- 발급한다 — 그래야 이미 받은 의견이 남는다.
CREATE TABLE collab_sessions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id  BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    share_token VARCHAR(255) NOT NULL,
    revoked_at  TIMESTAMP(6) WITH TIME ZONE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    -- 토큰으로만 찾는 유일한 키다. 없으면 같은 토큰이 두 세션에 붙어도 조용히 넘어간다.
    CONSTRAINT uk_collab_sessions_share_token UNIQUE (share_token),
    CONSTRAINT fk_collab_sessions_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE
);

CREATE INDEX idx_collab_sessions_gallery_id ON collab_sessions (gallery_id);

-- 하객에게 보여줄 사진. 갤러리 전체가 아니라 부부가 골라 담은 것만 보인다.
-- 수천 장을 하객에게 다 보여주면 아무도 끝까지 보지 않고, 부부가 묻고 싶은 것은 대개
-- "추리다 만 열 장 중 어느 것"이다.
--
-- 유니크가 (세션, 사진)이라 같은 사진이 여러 세션에 담긴다. 같은 사진을 부모님께도 친구들에게도
-- 물을 수 있어야 하고, 그때 두 쪽의 의견은 따로 모여야 한다.
--
-- photo_folders를 가리키지 않는다. 폴더에서 세션을 열 때는 그 시점의 사진을 이 표로 **복사**한다.
-- 가리키게 두면 부부가 폴더를 고치거나 지웠을 때 하객이 보던 사진이 발밑에서 바뀌고, 이미 받은
-- 댓글이 어느 사진에 달린 것인지 알 수 없게 된다. 폴더가 클러스터를 가리키지 않는 것과 같은 이유다.
CREATE TABLE collab_photos
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collab_session_id BIGINT NOT NULL,
    photo_id          BIGINT NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE,
    updated_at        TIMESTAMP(6) WITH TIME ZONE,
    -- 같은 사진이 두 번 담기면 하객에게 같은 사진이 두 번 보이고 반응도 둘로 갈린다.
    -- 애플리케이션이 갤러리 행을 잠그고 먼저 막지만, 여기가 마지막 방어선이다.
    CONSTRAINT uk_collab_photos_session_photo UNIQUE (collab_session_id, photo_id),
    CONSTRAINT fk_collab_photos_session
        FOREIGN KEY (collab_session_id) REFERENCES collab_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_collab_photos_photo
        FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE
);

CREATE INDEX idx_collab_photos_collab_session_id ON collab_photos (collab_session_id);

-- 하객 한 사람. 닉네임을 적고 들어오면 서버가 guest_token을 발급한다.
--
-- 닉네임을 댓글·투표 행에 복사하지 않고 여기 한 곳에만 둔다. 복사해두면 같은 사람이 댓글마다
-- 다른 이름을 쓸 수 있고, 이름을 고쳤을 때 과거 댓글이 남이 쓴 것처럼 보인다.
--
-- 토큰을 클라이언트가 만들지 않고 서버가 발급하는 이유는 이것이 약하게나마 "본인"의 근거이기
-- 때문이다. 값을 스스로 정할 수 있으면 남의 닉네임으로 글을 쓰거나 남의 표를 뒤집을 수 있다.
CREATE TABLE collab_guests
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collab_session_id BIGINT       NOT NULL,
    guest_token       VARCHAR(255) NOT NULL,
    nickname          VARCHAR(20)  NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE,
    updated_at        TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_collab_guests_guest_token UNIQUE (guest_token),
    CONSTRAINT fk_collab_guests_session
        FOREIGN KEY (collab_session_id) REFERENCES collab_sessions (id) ON DELETE CASCADE
);

CREATE INDEX idx_collab_guests_collab_session_id ON collab_guests (collab_session_id);

CREATE TABLE collab_photo_comments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collab_photo_id BIGINT       NOT NULL,
    collab_guest_id BIGINT       NOT NULL,
    -- 한 줄 감상이 아니라 문장이 오간다. 255자로 잡으면 하객이 쓰다 말고 잘린다.
    content         VARCHAR(500) NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_collab_photo_comments_collab_photo
        FOREIGN KEY (collab_photo_id) REFERENCES collab_photos (id) ON DELETE CASCADE,
    CONSTRAINT fk_collab_photo_comments_collab_guest
        FOREIGN KEY (collab_guest_id) REFERENCES collab_guests (id) ON DELETE CASCADE
);

CREATE INDEX idx_collab_photo_comments_collab_photo_id ON collab_photo_comments (collab_photo_id);

-- 사진에 대한 반응. 하객 한 사람이 사진 하나에 하나만 남긴다.
--
-- (collab_photo_id, collab_guest_id) 유니크가 이 표의 전부다. 없으면 새로고침할 때마다 표가
-- 쌓여서 "좋아요 40"이 사람 40명이 아니게 되고, 그 수를 보고 사진을 고르는 부부가 속는다.
-- 마음이 바뀌면 새 행이 아니라 reaction을 덮어쓴다.
CREATE TABLE collab_photo_votes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collab_photo_id BIGINT      NOT NULL,
    collab_guest_id BIGINT      NOT NULL,
    reaction        VARCHAR(20) NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_collab_photo_votes_photo_guest UNIQUE (collab_photo_id, collab_guest_id),
    -- 애플리케이션(CollabReaction)이 먼저 막지만, 그 검증은 그 문을 지날 때만 돈다.
    CONSTRAINT ck_collab_photo_votes_reaction CHECK (reaction IN ('GOOD', 'SOSO', 'BAD')),
    CONSTRAINT fk_collab_photo_votes_collab_photo
        FOREIGN KEY (collab_photo_id) REFERENCES collab_photos (id) ON DELETE CASCADE,
    CONSTRAINT fk_collab_photo_votes_collab_guest
        FOREIGN KEY (collab_guest_id) REFERENCES collab_guests (id) ON DELETE CASCADE
);

CREATE INDEX idx_collab_photo_votes_collab_photo_id ON collab_photo_votes (collab_photo_id);
