-- 하객 협업 세션. 로그인하지 않는 하객·부모님이 링크로 들어와 사진에 의견을 남긴다.
--
-- gallery_members에 얹지 않은 이유는 user_id가 NOT NULL이기 때문이다. 계정이 없는 사람은
-- 멤버 행 자체를 만들 수 없어서, 하객 참여는 멤버십이 아니라 갤러리에 붙는 능력으로 다룬다.
--
-- 갤러리당 세션 하나(uk_collab_sessions_gallery_id). 여러 개를 허용하면 "이 갤러리의 하객
-- 의견"이 어느 세션 것인지가 화면마다 갈린다. 링크가 퍼졌을 때는 세션을 새로 만드는 것이
-- 아니라 revoked_at을 세우고 share_token만 새로 발급한다 — 그래야 이미 받은 의견이 남는다.
CREATE TABLE collab_sessions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id  BIGINT       NOT NULL,
    share_token VARCHAR(255) NOT NULL,
    revoked_at  TIMESTAMP(6) WITH TIME ZONE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_collab_sessions_gallery_id UNIQUE (gallery_id),
    -- 토큰으로만 찾는 유일한 키다. 없으면 같은 토큰이 두 세션에 붙어도 조용히 넘어간다.
    CONSTRAINT uk_collab_sessions_share_token UNIQUE (share_token),
    CONSTRAINT fk_collab_sessions_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE
);

-- 하객에게 보여줄 사진. 갤러리 전체가 아니라 부부가 골라 담은 것만 보인다.
-- 수천 장을 하객에게 다 보여주면 아무도 끝까지 보지 않고, 부부가 묻고 싶은 것은 대개
-- "추리다 만 열 장 중 어느 것"이다.
CREATE TABLE collab_photos
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collab_session_id BIGINT NOT NULL,
    photo_id          BIGINT NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE,
    updated_at        TIMESTAMP(6) WITH TIME ZONE,
    -- 같은 사진이 두 번 담기면 하객에게 같은 사진이 두 번 보이고 반응도 둘로 갈린다.
    -- 애플리케이션이 갤러리 행을 잠그고 먼저 막지만, 여기가 마지막 방어선이다.
    CONSTRAINT uk_collab_photos_session_photo UNIQUE (collab_session_id, photo_id),
    CONSTRAINT fk_collab_photos_session
        FOREIGN KEY (collab_session_id) REFERENCES collab_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_collab_photos_photo
        FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE
);

CREATE INDEX idx_collab_photos_collab_session_id ON collab_photos (collab_session_id);

-- 하객 한 사람. 닉네임을 적고 들어오면 서버가 guest_token을 발급한다.
--
-- 닉네임을 댓글·투표 행에 복사하지 않고 여기 한 곳에만 둔다. 복사해두면 같은 사람이 댓글마다
-- 다른 이름을 쓸 수 있고, 이름을 고쳤을 때 과거 댓글이 남이 쓴 것처럼 보인다.
--
-- 토큰을 클라이언트가 만들지 않고 서버가 발급하는 이유는 이것이 약하게나마 "본인"의 근거이기
-- 때문이다. 값을 스스로 정할 수 있으면 남의 닉네임으로 글을 쓰거나 남의 표를 뒤집을 수 있다.
CREATE TABLE collab_guests
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collab_session_id BIGINT       NOT NULL,
    guest_token       VARCHAR(255) NOT NULL,
    nickname          VARCHAR(20)  NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE,
    updated_at        TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_collab_guests_guest_token UNIQUE (guest_token),
    CONSTRAINT fk_collab_guests_session
        FOREIGN KEY (collab_session_id) REFERENCES collab_sessions (id) ON DELETE CASCADE
);

CREATE INDEX idx_collab_guests_collab_session_id ON collab_guests (collab_session_id);

CREATE TABLE collab_photo_comments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collab_photo_id BIGINT       NOT NULL,
    collab_guest_id BIGINT       NOT NULL,
    -- 한 줄 감상이 아니라 문장이 오간다. 255자로 잡으면 하객이 쓰다 말고 잘린다.
    content         VARCHAR(500) NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_collab_photo_comments_collab_photo
        FOREIGN KEY (collab_photo_id) REFERENCES collab_photos (id) ON DELETE CASCADE,
    CONSTRAINT fk_collab_photo_comments_collab_guest
        FOREIGN KEY (collab_guest_id) REFERENCES collab_guests (id) ON DELETE CASCADE
);

CREATE INDEX idx_collab_photo_comments_collab_photo_id ON collab_photo_comments (collab_photo_id);

-- 사진에 대한 반응. 하객 한 사람이 사진 하나에 하나만 남긴다.
--
-- (collab_photo_id, collab_guest_id) 유니크가 이 표의 전부다. 없으면 새로고침할 때마다 표가
-- 쌓여서 "좋아요 40"이 사람 40명이 아니게 되고, 그 수를 보고 사진을 고르는 부부가 속는다.
-- 마음이 바뀌면 새 행이 아니라 reaction을 덮어쓴다.
CREATE TABLE collab_photo_votes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collab_photo_id BIGINT      NOT NULL,
    collab_guest_id BIGINT      NOT NULL,
    reaction        VARCHAR(20) NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_collab_photo_votes_photo_guest UNIQUE (collab_photo_id, collab_guest_id),
    -- 애플리케이션(CollabReaction)이 먼저 막지만, 그 검증은 그 문을 지날 때만 돈다.
    CONSTRAINT ck_collab_photo_votes_reaction CHECK (reaction IN ('GOOD', 'SOSO', 'BAD')),
    CONSTRAINT fk_collab_photo_votes_collab_photo
        FOREIGN KEY (collab_photo_id) REFERENCES collab_photos (id) ON DELETE CASCADE,
    CONSTRAINT fk_collab_photo_votes_collab_guest
        FOREIGN KEY (collab_guest_id) REFERENCES collab_guests (id) ON DELETE CASCADE
);

CREATE INDEX idx_collab_photo_votes_collab_photo_id ON collab_photo_votes (collab_photo_id);
