-- 기존 컨셉 공유는 그대로 두고, 연결이 없는 세션은 사진을 직접 담는 공유폴더로 쓴다.
ALTER TABLE collab_sessions ALTER COLUMN concept_folder_id DROP NOT NULL;
ALTER TABLE collab_sessions ADD CONSTRAINT uk_collab_sessions_id_gallery UNIQUE (id, gallery_id);
ALTER TABLE photos ADD CONSTRAINT uk_photos_id_gallery UNIQUE (id, gallery_id);

CREATE TABLE collab_session_photos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collab_session_id bigint NOT NULL,
    gallery_id bigint NOT NULL,
    photo_id bigint NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamptz,
    updated_at timestamptz,
    CONSTRAINT uk_collab_session_photos_session_photo UNIQUE (collab_session_id, photo_id),
    CONSTRAINT fk_collab_session_photos_session_gallery FOREIGN KEY (collab_session_id, gallery_id)
        REFERENCES collab_sessions(id, gallery_id) ON DELETE CASCADE,
    CONSTRAINT fk_collab_session_photos_photo_gallery FOREIGN KEY (photo_id, gallery_id)
        REFERENCES photos(id, gallery_id) ON DELETE CASCADE
);
CREATE INDEX idx_collab_session_photos_photo ON collab_session_photos(photo_id);
