-- 선호 가중치 레이어의 저장소.
--
-- 갤러리가 마감될 때마다 AI repo의 preference Lambda가 부부의 최종 선택(photo_selection_items)으로
-- 로지스틱 회귀 가중치 한 행을 다시 학습해 여기에 INSERT 한다. 게이트를 통과한 실행만 active=true 이고,
-- 그때 이전 active 행을 같은 트랜잭션에서 내린다 — 활성 행은 언제나 하나 이하다. 이 서버는 읽기만 한다:
-- 추천 잡이 embedding_model·model_version 이 photo_analysis 와 같은 active 행을 읽어 사진마다
-- 내적 한 번(w_scalar·x_scalar + w_emb·x_emb + bias)으로 pref 항을 만든다. 맞는 행이 없으면 지금 추천 그대로다.
--
-- w_emb 는 DINOv3(embedding) ⊕ CLIP(clip_embedding) 순서라 차원이 EMBEDDING_DIMENSION × 2 다.
-- feature_spec 은 x 의 자리 순서 계약(AI repo preference/features.py)이고, 학습기와 이 서버가 같은 값을 써야 한다.
CREATE TABLE preference_models (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    embedding_model varchar(60) NOT NULL,
    model_version varchar(40) NOT NULL,
    feature_spec varchar(40) NOT NULL,
    w_scalar double precision[] NOT NULL,
    w_emb vector(1536) NOT NULL,
    bias double precision NOT NULL,
    lambda double precision NOT NULL,
    n_galleries integer NOT NULL,
    n_positives integer NOT NULL,
    train_gallery_ids bigint[] NOT NULL,
    holdout jsonb NOT NULL,
    active boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_preference_models_active ON preference_models (active) WHERE active;

-- preference Lambda 는 score·categorize 와 같은 DB 유저(photoselect)로 붙는다. 학습기가 읽는
-- galleries·photos·photo_analysis·photo_selections·photo_selection_items 의 SELECT 는 V1 계약에 이미 있고,
-- 여기서는 새 테이블만 연다. role 은 Terraform 밖의 수동 생성이라 마이그레이션 시점에 있을 때만 건다.
-- PREFERENCE_GRANT_CONTRACT_BEGIN
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'photoselect') THEN
        EXECUTE 'GRANT SELECT, INSERT, UPDATE ON public.preference_models TO photoselect';
    END IF;
END
$$;
-- PREFERENCE_GRANT_CONTRACT_END
