-- 폴더를 부모폴더-자식폴더-사진의 2단계 구조로 재설계한다.
--
-- 클러스터링 결과를 고정하면 부모폴더 하나 아래 클러스터별 자식폴더들이 스냅샷으로 내려앉는다.
-- 부모는 이름과 id만 가지고 사진을 직접 담지 않으며, 사진은 항상 자식폴더에 담긴다.
-- 기존 flat 폴더는 운영 데이터가 아니므로 마이그레이션 없이 버리고 다시 만든다.
DROP TABLE IF EXISTS photo_folder_items;
DROP TABLE IF EXISTS photo_folders;

-- 부모폴더. 자식폴더들을 품는 이름표이며 사진을 직접 담지 않는다.
CREATE TABLE photo_folder_groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id BIGINT       NOT NULL,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_photo_folder_groups_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE
);

-- 부모폴더 목록은 항상 갤러리 단위로 읽는다.
CREATE INDEX idx_photo_folder_groups_gallery_id ON photo_folder_groups (gallery_id);

-- 자식폴더. 부모 없는 자식은 허용하지 않으므로 group_id가 NOT NULL이다.
-- gallery_id를 함께 두는 것은 (id, gallery_id) 조회 때문이다 -- 인가가 갤러리 단위라,
-- 협업 세션 시드처럼 갤러리와 폴더만 아는 호출자가 부모를 거치지 않고 폴더를 확인한다.
CREATE TABLE photo_folders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT       NOT NULL,
    gallery_id BIGINT       NOT NULL,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_photo_folders_group
        FOREIGN KEY (group_id) REFERENCES photo_folder_groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_photo_folders_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE
);

CREATE INDEX idx_photo_folders_group_id ON photo_folders (group_id);
CREATE INDEX idx_photo_folders_gallery_id ON photo_folders (gallery_id);

-- 자식폴더에 담긴 사진 한 장. group_id는 folder_id로도 알 수 있는 값이지만 행에 함께 둔다 --
-- "같은 부모 아래 자식들 간에는 사진이 중복될 수 없다"는 정책의 단위가 부모라서, 그 제약을
-- DB가 지키려면 부모 id가 이 행에 있어야 한다. 자식폴더는 부모를 옮겨 다니지 않으므로
-- 두 값이 어긋날 일은 없다.
CREATE TABLE photo_folder_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT NOT NULL,
    folder_id  BIGINT NOT NULL,
    photo_id   BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_photo_folder_items_group
        FOREIGN KEY (group_id) REFERENCES photo_folder_groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_photo_folder_items_folder
        FOREIGN KEY (folder_id) REFERENCES photo_folders (id) ON DELETE CASCADE,
    CONSTRAINT fk_photo_folder_items_photo
        FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE,
    -- 부모 스코프 중복 금지. 같은 자식에 두 번 넣는 것도 이 제약에 포섭된다.
    -- 서로 다른 부모끼리는 같은 사진을 얼마든지 담을 수 있다.
    CONSTRAINT uk_photo_folder_items_group_id_photo_id UNIQUE (group_id, photo_id)
);

-- 폴더 하나를 여는 질의. 위 유니크의 선두 컬럼이 group_id라 folder_id 조회를 받지 못한다.
CREATE INDEX idx_photo_folder_items_folder_id ON photo_folder_items (folder_id);
