-- 지금까지 `ddl-auto`가 만들어 오던 스키마를 그대로 옮긴 것이다.
--
-- **모든 문장이 `IF NOT EXISTS`다.** 이 파일은 이미 테이블이 있는 DB(운영)에서도 실행되며,
-- 없는 것만 채우고 있는 것은 건드리지 않는다.
--
-- 처음에는 `baseline-version: 1`로 두어 운영에서는 이 파일을 아예 건너뛰게 했었다. 그 방식은
-- "스키마가 비어 있지 않다"는 사실만으로 "V1이 이미 적용됐다"고 단정하는데, 그 단정은 검증되지
-- 않는다. 실제로 로컬에서 7개 중 2개 테이블만 있는 DB가 V1을 건너뛰었고, `photos`가 없는 채로
-- V2가 실행돼 깨졌다. 가정 대신 실행으로 맞추는 편이 어떤 상태의 DB에서도 수렴한다.
--
-- 한계: 테이블이 이미 있지만 컬럼이 다른 경우는 `IF NOT EXISTS`가 손대지 않는다. 그건
-- `ddl-auto: validate`가 기동 시점에 잡는다.
--
-- 새로 추가하는 마이그레이션(V2 이후)은 이렇게 쓰지 않는다. 그쪽은 "아직 없는 변경"을
-- 기술하는 것이라 이미 있다면 그 자체가 이상 신호이고, 조용히 넘기면 안 된다.
--
-- 외래키가 없는 것은 의도다. 엔티티가 연관관계 대신 `gallery_id` 같은 Long 컬럼을 들고 있어
-- Hibernate도 외래키를 만들지 않았다. 여기서 새로 걸면 이 파일이 실행되지 않는 기존 테이블에만
-- 제약이 없는 상태가 되어, 같은 코드가 환경에 따라 다르게 동작하게 된다.

CREATE TABLE IF NOT EXISTS users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider    VARCHAR(255) NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    nickname    VARCHAR(50)  NOT NULL,
    email       VARCHAR(255),
    role        VARCHAR(20)  NOT NULL,
    user_type   VARCHAR(20),
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_users_provider_provider_id UNIQUE (provider, provider_id)
);

CREATE TABLE IF NOT EXISTS refresh_tokens
(
    user_id    BIGINT PRIMARY KEY,
    token      VARCHAR(512)             NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS studios
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    name           VARCHAR(255) NOT NULL,
    gallery_url    VARCHAR(255) NOT NULL,
    inflow_channel VARCHAR(255),
    created_at     TIMESTAMP(6) WITH TIME ZONE,
    updated_at     TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_studios_user_id UNIQUE (user_id),
    CONSTRAINT uk_studios_gallery_url UNIQUE (gallery_url)
);

CREATE TABLE IF NOT EXISTS galleries
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    studio_id          BIGINT       NOT NULL,
    title              VARCHAR(100) NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    selection_deadline TIMESTAMP(6) WITH TIME ZONE,
    created_at         TIMESTAMP(6) WITH TIME ZONE,
    updated_at         TIMESTAMP(6) WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_galleries_studio_id ON galleries (studio_id);

CREATE TABLE IF NOT EXISTS gallery_members
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_gallery_members_gallery_id_user_id UNIQUE (gallery_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_gallery_members_user_id ON gallery_members (user_id);

CREATE TABLE IF NOT EXISTS gallery_invites
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id BIGINT                      NOT NULL,
    token      VARCHAR(255)                NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_gallery_invites_token UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS idx_gallery_invites_gallery_id ON gallery_invites (gallery_id);

CREATE TABLE IF NOT EXISTS photos
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id         BIGINT       NOT NULL,
    storage_key        VARCHAR(500) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    display_order      INTEGER      NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE,
    updated_at         TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_photos_storage_key UNIQUE (storage_key)
);

CREATE INDEX IF NOT EXISTS idx_photos_gallery_id ON photos (gallery_id);
