-- 셀렉 확정 전에 부부가 보정을 요청하는 흐름. 보정사진 풀에 모아두고 회차 단위로 일괄
-- 제출하면 작가가 회차 단위로 결과를 올린다.
--
-- 보정 결과를 photos에 넣지 않는다. photos에 들어가는 순간 갤러리 사진 목록·클러스터링
-- (임베딩 재실행 시 보정본까지 임베딩됨)·별점·휴지통 전부가 "보정본 제외" 분기를 갖게 된다.
-- 대신 보정 도메인이 결과 파일의 storage key를 직접 들고, photos는 원본만 담는 불변식을
-- 유지한다.

-- 계약상 보정 요청 가능 횟수. 작가가 정하고 부부는 바꿀 수 없다.
-- 갤러리에 두는 이유는 target_photo_count(V7, 현 max_selectable_photo_count)와 같다 --
-- 이 값은 계약에서 나오지 보정 과정에서 나오지 않는다. NULL은 "제한 없음"이다.
ALTER TABLE galleries
    ADD COLUMN max_retouch_round_count INTEGER;

-- 보정 회차. 갤러리당 동시에 하나만 진행한다(DRAFTING -> REQUESTED -> COMPLETED).
-- 새 회차는 이전 회차가 COMPLETED일 때만 생긴다 -- 결과가 오기 전에 다음 요청이 쌓이면
-- "몇 회 남았는지"가 흐려지고 회차별 전/후 비교의 전제도 깨진다.
CREATE TABLE retouch_rounds
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id   BIGINT      NOT NULL,
    round_no     INTEGER     NOT NULL,
    status       VARCHAR(20) NOT NULL,
    -- 부부가 제출한 시각. 회차가 REQUESTED가 되는 순간 채워진다.
    requested_at TIMESTAMP(6) WITH TIME ZONE,
    -- 작가가 회차를 끝낸 시각.
    completed_at TIMESTAMP(6) WITH TIME ZONE,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_retouch_rounds_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE,
    -- 회차 번호는 갤러리 안에서 유일하다. 애플리케이션은 갤러리 행을 잠그고 번호를 매기지만,
    -- 잠금을 빠뜨린 경로가 생기면 같은 번호가 둘이 되고 그때는 어느 쪽이 몇 회차인지 알 수
    -- 없다. DB가 마지막으로 막는다. 갤러리 단독 조회도 이 제약이 만드는 인덱스가 받는다.
    CONSTRAINT uk_retouch_rounds_gallery_round UNIQUE (gallery_id, round_no)
);

-- 회차에 담긴 보정 요청 한 건. 요청 내용(텍스트·주석 이미지 key)과 작가가 올린 결과 key를
-- 함께 든다. gallery_id는 round_id로도 알 수 있는 값이지만 행에 함께 둔다 --
-- 갤러리 스코프 조회(그리드·정리)가 회차를 거치지 않고 항목을 읽는다(photo_folder_items 전례).
CREATE TABLE retouch_photos
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id            BIGINT NOT NULL,
    gallery_id          BIGINT NOT NULL,
    photo_id            BIGINT NOT NULL,
    request_text        TEXT,
    -- 프론트가 캔버스로 그린 주석 레이어 PNG의 storage key. 서버는 key만 저장한다.
    annotation_key      VARCHAR(500),
    -- 작가가 올린 보정 결과 파일의 storage key. NULL이면 아직 응답이 없는 항목이다.
    result_key          VARCHAR(500),
    result_content_type VARCHAR(100),
    created_at          TIMESTAMP(6) WITH TIME ZONE,
    updated_at          TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_retouch_photos_round
        FOREIGN KEY (round_id) REFERENCES retouch_rounds (id) ON DELETE CASCADE,
    CONSTRAINT fk_retouch_photos_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE,
    CONSTRAINT fk_retouch_photos_photo
        FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE,
    -- 같은 회차에 같은 사진을 두 번 넣는 것은 중복 요청이다. 회차가 다르면 같은 사진을
    -- 다시 넣을 수 있다 -- 1회차 결과가 미흡했던 컷을 2회차에 재보정하는 흐름이 있다.
    CONSTRAINT uk_retouch_photos_round_photo UNIQUE (round_id, photo_id)
);

CREATE INDEX idx_retouch_photos_gallery_id ON retouch_photos (gallery_id);
-- 사진 휴지통 비우기가 ON DELETE CASCADE로 이 테이블을 지운다. 인덱스가 없으면 사진 한 장을
-- 지울 때마다 전체 스캔이다.
CREATE INDEX idx_retouch_photos_photo_id ON retouch_photos (photo_id);
