CREATE TABLE admin_accounts
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username              VARCHAR(64)              NOT NULL,
    display_name          VARCHAR(50)              NOT NULL,
    password_hash         VARCHAR(255)             NOT NULL,
    status                VARCHAR(20)              NOT NULL,
    must_change_password  BOOLEAN                  NOT NULL DEFAULT TRUE,
    failed_login_attempts INTEGER                  NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP WITH TIME ZONE,
    password_changed_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    last_login_at         TIMESTAMP WITH TIME ZONE,
    created_by_admin_id   BIGINT,
    created_at            TIMESTAMP WITH TIME ZONE,
    updated_at            TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_admin_accounts_username UNIQUE (username),
    CONSTRAINT ck_admin_accounts_username_lowercase CHECK (username = lower(username)),
    CONSTRAINT ck_admin_accounts_failed_login_attempts CHECK (failed_login_attempts >= 0)
);

CREATE TABLE admin_sessions
(
    token_hash          VARCHAR(64)              PRIMARY KEY,
    admin_id            BIGINT                   NOT NULL,
    last_active_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    absolute_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at          TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE,
    updated_at          TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_admin_sessions_admin
        FOREIGN KEY (admin_id) REFERENCES admin_accounts (id) ON DELETE CASCADE
);

CREATE INDEX idx_admin_sessions_admin_id ON admin_sessions (admin_id);
CREATE INDEX idx_admin_sessions_expiration ON admin_sessions (absolute_expires_at);

CREATE TABLE admin_auth_events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type        VARCHAR(40)              NOT NULL,
    actor_admin_id    BIGINT,
    target_admin_id   BIGINT,
    username_snapshot VARCHAR(64),
    source_address    VARCHAR(64),
    reason            VARCHAR(500),
    successful        BOOLEAN                  NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_admin_auth_events_created_at ON admin_auth_events (created_at DESC);
CREATE INDEX idx_admin_auth_events_actor_admin_id ON admin_auth_events (actor_admin_id);
CREATE INDEX idx_admin_auth_events_target_admin_id ON admin_auth_events (target_admin_id);
