CREATE TABLE admin_audit_logs
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action                  VARCHAR(60)              NOT NULL,
    outcome                 VARCHAR(20)              NOT NULL,
    actor_admin_id          BIGINT,
    actor_username_snapshot VARCHAR(64),
    target_type             VARCHAR(60),
    target_id               VARCHAR(128),
    target_label            VARCHAR(120),
    source_address          VARCHAR(64),
    reason                  VARCHAR(500),
    changed_fields          VARCHAR(1000),
    revision_number         BIGINT,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_admin_audit_logs_created_at ON admin_audit_logs (created_at DESC);
CREATE INDEX idx_admin_audit_logs_actor ON admin_audit_logs (actor_admin_id, created_at DESC);
CREATE INDEX idx_admin_audit_logs_target ON admin_audit_logs (target_type, target_id, created_at DESC);
CREATE INDEX idx_admin_audit_logs_action ON admin_audit_logs (action, created_at DESC);

CREATE TABLE admin_entity_revisions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type      VARCHAR(60)              NOT NULL,
    target_id        VARCHAR(128)             NOT NULL,
    revision_number  BIGINT                   NOT NULL,
    operation        VARCHAR(60)              NOT NULL,
    before_snapshot  TEXT,
    after_snapshot   TEXT,
    expires_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_admin_entity_revisions_target_revision
        UNIQUE (target_type, target_id, revision_number)
);

CREATE INDEX idx_admin_entity_revisions_target
    ON admin_entity_revisions (target_type, target_id, revision_number DESC);
CREATE INDEX idx_admin_entity_revisions_expires_at
    ON admin_entity_revisions (expires_at);

-- WES-250에서 이미 쌓인 인증·계정 이벤트도 새 감사 조회 화면에서 끊김 없이 보이게 한다.
INSERT INTO admin_audit_logs
(
    action,
    outcome,
    actor_admin_id,
    actor_username_snapshot,
    target_type,
    target_id,
    target_label,
    source_address,
    reason,
    changed_fields,
    revision_number,
    created_at,
    updated_at
)
SELECT event_type,
       CASE WHEN successful THEN 'SUCCESS' ELSE 'FAILURE' END,
       actor_admin_id,
       username_snapshot,
       CASE WHEN target_admin_id IS NULL THEN 'AUTHENTICATION' ELSE 'ADMIN_ACCOUNT' END,
       COALESCE(target_admin_id::TEXT, username_snapshot),
       username_snapshot,
       source_address,
       reason,
       NULL,
       NULL,
       created_at,
       updated_at
FROM admin_auth_events;

-- 감사 로그는 애플리케이션 계정으로도 수정·삭제할 수 없다. 테스트 정리는 TRUNCATE를 사용하고,
-- 운영 보존 정책 또한 테이블 자체를 건드리지 않으므로 이 트리거와 충돌하지 않는다.
CREATE FUNCTION prevent_admin_audit_log_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'admin_audit_logs are immutable';
END;
$$;

CREATE TRIGGER trg_admin_audit_logs_immutable
BEFORE UPDATE OR DELETE ON admin_audit_logs
FOR EACH ROW
EXECUTE FUNCTION prevent_admin_audit_log_mutation();
