-- 관리자 변경 API의 expectedVersion은 일반 사용자 경로에서 일어난 변경도 감지해야 한다.
-- 모든 BaseEntity 테이블에 Hibernate @Version 컬럼을 같은 기본값으로 추가한다.
ALTER TABLE users ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE refresh_tokens ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE studios ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE galleries ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE gallery_members ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE gallery_invites ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE photos ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE oauth_states ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE photo_folders ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE photo_folder_groups ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE photo_folder_items ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE photo_selections ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE photo_selection_items ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE photo_ratings ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE collab_sessions ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE collab_photos ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE collab_guests ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE collab_photo_comments ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE collab_photo_likes ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE retouch_rounds ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE retouch_photos ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE admin_accounts ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE admin_sessions ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE admin_auth_events ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE admin_audit_logs ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE admin_entity_revisions ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

-- 외부 재처리 호출은 DB의 유니크 키를 먼저 선점한다. 같은 key/action 조합은 한 번만 실행된다.
CREATE TABLE admin_idempotency_keys
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action            VARCHAR(60)              NOT NULL,
    idempotency_key   VARCHAR(128)             NOT NULL,
    request_hash      VARCHAR(64)              NOT NULL,
    status            VARCHAR(20)              NOT NULL,
    result_payload    TEXT,
    failure_code      VARCHAR(80),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_admin_idempotency_action_key UNIQUE (action, idempotency_key),
    CONSTRAINT ck_admin_idempotency_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idx_admin_idempotency_created_at ON admin_idempotency_keys (created_at);
