-- 최고 관리자 삭제는 모든 주요 데이터에 동일한 7일 복구 창을 제공한다.
-- 루트와 함께 숨긴 자식의 목록을 배치로 고정해 복원 시 기존의 개별 휴지통 상태를 침범하지 않는다.
ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE studios ADD COLUMN deleted_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE photo_selections ADD COLUMN deleted_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE collab_sessions ADD COLUMN deleted_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE photo_folder_groups ADD COLUMN deleted_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE retouch_rounds ADD COLUMN deleted_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE collab_photo_comments ADD COLUMN deleted_at TIMESTAMP(6) WITH TIME ZONE;

CREATE INDEX idx_users_deleted_at ON users (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_studios_deleted_at ON studios (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_photo_selections_deleted_at ON photo_selections (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_collab_sessions_deleted_at ON collab_sessions (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_photo_folder_groups_deleted_at ON photo_folder_groups (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_retouch_rounds_deleted_at ON retouch_rounds (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_collab_photo_comments_deleted_at ON collab_photo_comments (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE TABLE admin_trash_batches
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    root_type        VARCHAR(40)              NOT NULL,
    root_id          BIGINT                   NOT NULL,
    root_label       VARCHAR(500)             NOT NULL,
    actor_admin_id   BIGINT,
    actor_username   VARCHAR(64),
    reason           VARCHAR(500)             NOT NULL,
    status           VARCHAR(20)              NOT NULL,
    deleted_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    restore_until    TIMESTAMP WITH TIME ZONE NOT NULL,
    restored_at      TIMESTAMP WITH TIME ZONE,
    purged_at        TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_admin_trash_batch_status CHECK (status IN ('ACTIVE', 'RESTORED', 'PURGED'))
);

CREATE UNIQUE INDEX uk_admin_trash_active_root
    ON admin_trash_batches (root_type, root_id)
    WHERE status = 'ACTIVE';
CREATE INDEX idx_admin_trash_restore_until
    ON admin_trash_batches (restore_until)
    WHERE status = 'ACTIVE';

CREATE TABLE admin_trash_entries
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id      BIGINT      NOT NULL,
    resource_type VARCHAR(40) NOT NULL,
    resource_id   BIGINT      NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_admin_trash_entries_batch
        FOREIGN KEY (batch_id) REFERENCES admin_trash_batches (id) ON DELETE CASCADE,
    CONSTRAINT uk_admin_trash_entry UNIQUE (batch_id, resource_type, resource_id)
);

CREATE INDEX idx_admin_trash_entries_resource
    ON admin_trash_entries (resource_type, resource_id);
