ALTER TABLE galleries ADD COLUMN plan_type varchar(10)
    CHECK (plan_type IN ('FREE', 'PRO'));

CREATE TABLE free_gallery_claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    gallery_id bigint REFERENCES galleries(id) ON DELETE SET NULL,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE pro_coupons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash varchar(64) NOT NULL UNIQUE CHECK (code_hash ~ '^[0-9a-f]{64}$'),
    user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    registered_at timestamptz,
    consumed_at timestamptz,
    gallery_id bigint REFERENCES galleries(id) ON DELETE SET NULL,
    expires_at timestamptz,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (user_id IS NULL OR registered_at IS NOT NULL),
    CHECK (consumed_at IS NULL OR registered_at IS NOT NULL),
    CHECK ((consumed_at IS NULL) = (expires_at IS NULL)),
    CHECK (gallery_id IS NULL OR consumed_at IS NOT NULL),
    CHECK (expires_at IS NULL OR expires_at > consumed_at)
);
CREATE INDEX idx_pro_coupons_user_id ON pro_coupons(user_id);
