-- 최고 관리자 운영 화면에서 실행하는 도메인별 복구 작업과 리비전을 기록한다.

ALTER TABLE admin_idempotency_keys DROP CONSTRAINT ck_admin_idempotency_status;
ALTER TABLE admin_idempotency_keys
    ADD CONSTRAINT ck_admin_idempotency_status
        CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'CANCELED'));

-- status는 초대 사용자가 볼 수 있는 공개 단계(DRAFT/OPEN/CLOSED)다. 운영 진행 단계는
-- 별도 컬럼으로 분리해 "공개는 닫았지만 납품 작업은 진행 중" 같은 상태를 잃지 않는다.
ALTER TABLE galleries
    ADD COLUMN workflow_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    ADD CONSTRAINT ck_galleries_workflow_status
        CHECK (workflow_status IN ('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED'));

-- 스튜디오의 기존 user_id는 소유자다. 추가 운영 구성원은 별도 관계로 관리한다.
CREATE TABLE studio_members
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    studio_id  BIGINT                   NOT NULL,
    user_id    BIGINT                   NOT NULL,
    role       VARCHAR(20)              NOT NULL,
    version    BIGINT                   NOT NULL DEFAULT 0,
    deleted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_studio_members_studio FOREIGN KEY (studio_id) REFERENCES studios (id) ON DELETE CASCADE,
    CONSTRAINT fk_studio_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_studio_members_studio_user UNIQUE (studio_id, user_id),
    CONSTRAINT ck_studio_members_role CHECK (role IN ('OWNER', 'MEMBER'))
);

CREATE INDEX idx_studio_members_user ON studio_members (user_id, studio_id);

-- 협업 링크도 초대와 동일하게 만료 시각을 가진다. 토큰 원문은 관리자 응답에 노출하지 않는다.
ALTER TABLE collab_sessions
    ADD COLUMN expires_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE admin_photo_revisions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_id           BIGINT                   NOT NULL,
    revision_number    BIGINT                   NOT NULL,
    storage_key        VARCHAR(500)             NOT NULL,
    preview_key        VARCHAR(500),
    original_file_name VARCHAR(255)             NOT NULL,
    content_type       VARCHAR(100)             NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_admin_photo_revisions_photo
        FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE,
    CONSTRAINT uk_admin_photo_revisions_photo_revision UNIQUE (photo_id, revision_number)
);

CREATE TABLE admin_photo_replacement_uploads
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_id           BIGINT                   NOT NULL,
    storage_key        VARCHAR(500)             NOT NULL,
    original_file_name VARCHAR(255)             NOT NULL,
    content_type       VARCHAR(100)             NOT NULL,
    status             VARCHAR(20)              NOT NULL,
    expires_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_admin_id     BIGINT,
    reason             VARCHAR(500)             NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_admin_photo_replacement_uploads_photo
        FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE,
    CONSTRAINT uk_admin_photo_replacement_storage_key UNIQUE (storage_key),
    CONSTRAINT ck_admin_photo_replacement_status CHECK (status IN ('PENDING', 'COMPLETED', 'EXPIRED'))
);

CREATE UNIQUE INDEX uk_admin_photo_replacement_pending
    ON admin_photo_replacement_uploads (photo_id)
    WHERE status = 'PENDING';

-- 외부 작업 실행 여부와 사용자에게 보이는 사진 상태를 분리한다. 디스패처가 없는 작업은
-- PENDING으로 남으며, 관리 API가 성공으로 위장하지 않는다.
CREATE TABLE admin_processing_jobs
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type       VARCHAR(40)              NOT NULL,
    status         VARCHAR(20)              NOT NULL,
    target_type    VARCHAR(40)              NOT NULL,
    target_id      BIGINT                   NOT NULL,
    revision_id    BIGINT,
    payload        JSONB                    NOT NULL DEFAULT '{}'::JSONB,
    attempt_count  INTEGER                  NOT NULL DEFAULT 0,
    failure_code   VARCHAR(80),
    last_run_at    TIMESTAMP WITH TIME ZONE,
    actor_admin_id BIGINT,
    reason         VARCHAR(500)             NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_admin_processing_job_type
        CHECK (job_type IN ('DERIVATIVE', 'EMBEDDING', 'QUALITY_ANALYSIS', 'MOCK_RECALCULATION')),
    CONSTRAINT ck_admin_processing_job_status
        CHECK (status IN ('PENDING', 'DISPATCHING', 'DISPATCHED', 'SUCCEEDED', 'FAILED', 'CANCELED'))
);

CREATE UNIQUE INDEX uk_admin_processing_job_revision_type
    ON admin_processing_jobs (job_type, target_type, target_id, revision_id)
    WHERE revision_id IS NOT NULL;
CREATE INDEX idx_admin_processing_jobs_target
    ON admin_processing_jobs (target_type, target_id, created_at DESC);

CREATE TABLE admin_notification_outbox
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_type    VARCHAR(80)              NOT NULL,
    recipient_reference  VARCHAR(255)             NOT NULL,
    source_type          VARCHAR(40)              NOT NULL,
    source_id            BIGINT                   NOT NULL,
    payload              JSONB                    NOT NULL DEFAULT '{}'::JSONB,
    status               VARCHAR(20)              NOT NULL,
    attempt_count        INTEGER                  NOT NULL DEFAULT 0,
    failure_code         VARCHAR(80),
    actor_admin_id       BIGINT,
    reason               VARCHAR(500)             NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_admin_notification_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'CANCELED'))
);

CREATE INDEX idx_admin_notification_source
    ON admin_notification_outbox (source_type, source_id, created_at DESC);

CREATE TABLE admin_selection_revisions
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selection_id      BIGINT                   NOT NULL,
    revision_number   BIGINT                   NOT NULL,
    source            VARCHAR(30)              NOT NULL,
    status            VARCHAR(20)              NOT NULL,
    photo_items       JSONB                    NOT NULL,
    actor_admin_id    BIGINT,
    reason            VARCHAR(500)             NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_admin_selection_revisions_selection
        FOREIGN KEY (selection_id) REFERENCES photo_selections (id) ON DELETE CASCADE,
    CONSTRAINT uk_admin_selection_revisions_selection_revision UNIQUE (selection_id, revision_number),
    CONSTRAINT ck_admin_selection_revision_source CHECK (source IN ('ADMIN', 'AI_DRAFT'))
);

CREATE FUNCTION reject_admin_selection_revision_update() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'admin selection revisions are immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_admin_selection_revisions_immutable
    BEFORE UPDATE ON admin_selection_revisions
    FOR EACH ROW EXECUTE FUNCTION reject_admin_selection_revision_update();

-- 실제 결정적 선택 계산의 입력, 결과, 실패를 별도 작업으로 남긴다. AI가 구성되지 않았거나
-- 임베딩 후보가 없으면 SUCCEEDED를 쓰지 않는다.
CREATE TABLE admin_ai_selection_jobs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selection_id       BIGINT                   NOT NULL,
    status             VARCHAR(20)              NOT NULL,
    input_conditions   JSONB                    NOT NULL,
    result_revision_id BIGINT,
    failure_code       VARCHAR(80),
    attempt_count      INTEGER                  NOT NULL DEFAULT 0,
    actor_admin_id     BIGINT,
    reason             VARCHAR(500)             NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at         TIMESTAMP WITH TIME ZONE,
    completed_at       TIMESTAMP WITH TIME ZONE,
    updated_at         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_admin_ai_selection_jobs_selection
        FOREIGN KEY (selection_id) REFERENCES photo_selections (id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_ai_selection_jobs_revision
        FOREIGN KEY (result_revision_id) REFERENCES admin_selection_revisions (id) ON DELETE SET NULL,
    CONSTRAINT ck_admin_ai_selection_job_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED'))
);

CREATE INDEX idx_admin_ai_selection_jobs_selection
    ON admin_ai_selection_jobs (selection_id, created_at DESC);

ALTER TABLE photo_folder_groups
    ADD COLUMN selection_revision_id BIGINT REFERENCES admin_selection_revisions (id) ON DELETE SET NULL,
    ADD COLUMN template_name VARCHAR(100),
    ADD COLUMN template_id BIGINT;

CREATE TABLE admin_album_templates
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)             NOT NULL,
    layout_json JSONB                    NOT NULL,
    version     BIGINT                   NOT NULL DEFAULT 0,
    deleted_at  TIMESTAMP WITH TIME ZONE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_admin_album_template_name UNIQUE (name)
);

ALTER TABLE photo_folder_groups
    ADD CONSTRAINT fk_photo_folder_groups_admin_template
        FOREIGN KEY (template_id) REFERENCES admin_album_templates (id) ON DELETE SET NULL;

ALTER TABLE photo_folder_items
    ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN crop_json JSONB;

ALTER TABLE retouch_rounds
    ADD COLUMN selection_revision_id BIGINT REFERENCES admin_selection_revisions (id) ON DELETE SET NULL,
    ADD COLUMN customer_consented_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN delivered_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN delivery_note VARCHAR(500);

ALTER TABLE retouch_photos
    ADD COLUMN structured_ai_metadata JSONB,
    ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE studio_retouch_capabilities
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    studio_id  BIGINT                   NOT NULL,
    capability VARCHAR(100)             NOT NULL,
    enabled    BOOLEAN                  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_studio_retouch_capabilities_studio
        FOREIGN KEY (studio_id) REFERENCES studios (id) ON DELETE CASCADE,
    CONSTRAINT uk_studio_retouch_capability UNIQUE (studio_id, capability)
);

CREATE INDEX idx_admin_photo_revisions_photo ON admin_photo_revisions (photo_id, revision_number DESC);
CREATE INDEX idx_admin_selection_revisions_selection ON admin_selection_revisions (selection_id, revision_number DESC);
CREATE INDEX idx_admin_album_templates_active ON admin_album_templates (deleted_at, name);
