-- WES-258/259/261: 관리자 세션 결속, 복원 가능한 리비전 스키마, 연쇄 휴지통 관계 사실,
-- 영구 감사 로그의 상관관계 경계를 추가한다. 기존 운영 행은 변경하지 않는다.

ALTER TABLE admin_sessions
    ADD COLUMN session_id UUID NOT NULL DEFAULT gen_random_uuid(),
    ADD CONSTRAINT uk_admin_sessions_session_id UNIQUE (session_id);

ALTER TABLE admin_impersonation_sessions
    ADD COLUMN admin_session_id UUID,
    ADD COLUMN viewer_user_id BIGINT,
    ADD COLUMN viewer_role VARCHAR(20),
    ADD COLUMN correlation_id VARCHAR(16),
    ADD CONSTRAINT fk_admin_impersonation_login_session
        FOREIGN KEY (admin_session_id) REFERENCES admin_sessions (session_id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_admin_impersonation_viewer
        FOREIGN KEY (viewer_user_id) REFERENCES users (id) ON DELETE SET NULL;

-- 신규 애플리케이션 행은 두 컬럼을 모두 채운다. 결속 정보가 없는 기존 행은 서버가 활성으로
-- 인정하지 않으므로 운영 중이던 세션을 추측으로 다른 로그인 세션에 연결하지 않는다.
CREATE UNIQUE INDEX uk_admin_impersonation_active_login_session
    ON admin_impersonation_sessions (admin_session_id)
    WHERE ended_at IS NULL AND admin_session_id IS NOT NULL;

CREATE INDEX idx_admin_impersonation_correlation
    ON admin_impersonation_sessions (correlation_id);

ALTER TABLE admin_audit_logs
    ADD COLUMN correlation_id VARCHAR(16),
    ADD COLUMN impersonation_session_id UUID;

CREATE INDEX idx_admin_audit_logs_correlation
    ON admin_audit_logs (correlation_id, created_at DESC);

-- correlation_id는 요청 하나의 16자리 MDC trace이고, 대리보기 생명주기 결속은 별도 UUID다.
-- 감사 로그는 영구 보관하므로 휘발성 대리보기 세션 테이블에 FK를 걸지 않는다.
CREATE INDEX idx_admin_audit_logs_impersonation_session
    ON admin_audit_logs (impersonation_session_id, created_at DESC);

ALTER TABLE admin_entity_revisions
    ADD COLUMN snapshot_schema_version INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN target_version BIGINT,
    ADD COLUMN before_restore_payload TEXT,
    ADD COLUMN after_restore_payload TEXT;

COMMENT ON COLUMN admin_entity_revisions.before_restore_payload IS
    'API에 노출하지 않는 7일 한정 복원 payload. secret 필드는 제외하며 revision row와 함께 purge한다.';
COMMENT ON COLUMN admin_entity_revisions.after_restore_payload IS
    'API에 노출하지 않는 7일 한정 복원 payload. secret 필드는 제외하며 revision row와 함께 purge한다.';

ALTER TABLE admin_trash_batches
    ADD COLUMN relationship_facts JSONB NOT NULL DEFAULT '{}'::JSONB;

ALTER TABLE admin_trash_entries
    ADD COLUMN is_root BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN relation_path VARCHAR(100);

CREATE INDEX idx_admin_trash_entries_batch_root
    ON admin_trash_entries (batch_id, is_root, resource_type);

-- 댓글·앨범 템플릿·보정 항목을 독립적으로 삭제한 경우에도 루트 연쇄 휴지통과 동일한
-- 7일 복원/8일차 purge 정책을 적용한다. 자식이나 부모 FK를 걸지 않아 부모 영구 삭제 뒤에도
-- purge 결과와 삭제자·사유를 추적할 수 있게 한다.
CREATE TABLE admin_child_trash_records
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type       VARCHAR(40)              NOT NULL,
    resource_id         BIGINT                   NOT NULL,
    parent_type         VARCHAR(40)              NOT NULL,
    parent_id           BIGINT                   NOT NULL,
    actor_admin_id      BIGINT,
    actor_username      VARCHAR(64),
    reason              VARCHAR(500)             NOT NULL,
    status              VARCHAR(20)              NOT NULL,
    deleted_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    restore_until       TIMESTAMP WITH TIME ZONE NOT NULL,
    restored_at         TIMESTAMP WITH TIME ZONE,
    purged_at           TIMESTAMP WITH TIME ZONE,
    purge_attempt_count INTEGER                   NOT NULL DEFAULT 0,
    purge_started_at    TIMESTAMP WITH TIME ZONE,
    failure_code        VARCHAR(120),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_admin_child_trash_actor
        FOREIGN KEY (actor_admin_id) REFERENCES admin_accounts (id) ON DELETE SET NULL,
    CONSTRAINT ck_admin_child_trash_resource_parent
        CHECK (
            (resource_type = 'COLLAB_COMMENT' AND parent_type = 'COLLABORATION')
            OR (resource_type = 'ALBUM_TEMPLATE' AND parent_type = 'ALBUM')
            OR (resource_type = 'RETOUCH_ITEM' AND parent_type = 'RETOUCH_REQUEST')
        ),
    CONSTRAINT ck_admin_child_trash_status
        CHECK (status IN ('ACTIVE', 'PURGING', 'RESTORED', 'PURGED'))
);

CREATE UNIQUE INDEX uk_admin_child_trash_active_resource
    ON admin_child_trash_records (resource_type, resource_id)
    WHERE status IN ('ACTIVE', 'PURGING');

CREATE INDEX idx_admin_child_trash_purge_claim
    ON admin_child_trash_records (status, restore_until, purge_started_at);

COMMENT ON COLUMN admin_trash_batches.restore_until IS
    'deleted_at부터 7일 동안 복원 가능하며 이 시각부터 8일차 영구 삭제 대상';
COMMENT ON COLUMN admin_trash_batches.relationship_facts IS
    '삭제 당시 관계·댓글·템플릿·리비전·스토리지 메타데이터 건수. 키나 본문은 저장하지 않는다.';
COMMENT ON COLUMN admin_child_trash_records.restore_until IS
    '독립 자식 삭제 시 deleted_at부터 7일 동안 복원 가능하며 이 시각부터 8일차 영구 삭제 대상';
