-- 분석 잡이 단계를 넘어갈 때마다 한 줄씩 남기는 이력.
--
-- analysis_jobs 행은 마지막 상태만 말하고, 단계별 시각·재전송·폴백·실패 이유는 로그에만 있었다(보관 7일).
-- 로그의 job.* · folder.materialized · score.fallback 과 같은 지점에서 같은 내용을 한 행씩 쓴다.
--
-- type:   AnalysisJobEventType 의 이름. CHECK 를 걸지 않는다 — 종류가 늘 때마다 마이그레이션을 쓰지 않으려는 것이고,
--         읽는 쪽(운영 조회)은 모르는 종류를 그대로 보여 주면 된다.
-- detail: 종류마다 다른 부가 값(장수·시도 횟수·오류 코드 등). 조회 조건으로 쓰지 않는다.
-- 잡이 지워지면(갤러리 삭제 포함) 같이 지워진다.
CREATE TABLE analysis_job_events (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id     bigint                      NOT NULL,
    gallery_id bigint                      NOT NULL,
    type       varchar(40)                 NOT NULL,
    detail     jsonb,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT fk_analysis_job_events_job FOREIGN KEY (job_id) REFERENCES analysis_jobs (id) ON DELETE CASCADE
);
-- 잡 하나의 타임라인을 순서대로 읽는다. 잡 삭제의 CASCADE 도 이 인덱스를 탄다.
CREATE INDEX idx_analysis_job_events_job ON analysis_job_events (job_id, id);
