-- 세부 폴더 합치기 기록. 웹의 "실행 취소"가 합치기를 되돌리는 재료다(#247).
--
-- 합치면 원본 세부 폴더는 지우지 않고 deleted_at 을 채워 숨긴다 — 되돌릴 때 id · sort_order · created_source 가 그대로 돌아오게 하려는 것이다.
-- 관리자 휴지통도 deleted_at 을 쓰지만, 관리자 복원은 admin_trash_entries 에 적힌 행만 되살리므로 합치기로 숨긴 폴더와 섞이지 않는다.
--
-- detail_folder_merge_photos: 이 합치기가 옮긴 사진과, 옮기기 전 배정 정보(누가 · 어떤 출처로 · 신뢰도 · 언제).
--   되돌리면 사진을 원본 폴더로 돌리며 이 값을 그대로 되살린다. 합칠 때 배정은 USER 로 덮어쓰이기 때문이다.
-- undone_at: 되돌린 시각. 한 합치기는 한 번만 되돌린다.
-- 원본 · 대상 폴더나 갤러리가 지워지면 기록도 같이 지워진다 — 되돌릴 곳이 없으면 기록도 쓸모가 없다.
CREATE TABLE detail_folder_merges (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id              bigint                      NOT NULL,
    source_detail_folder_id bigint                      NOT NULL,
    target_detail_folder_id bigint                      NOT NULL,
    merged_by_user_id       bigint,
    merged_at               timestamp(6) with time zone NOT NULL,
    undone_at               timestamp(6) with time zone,
    version                 bigint DEFAULT 0            NOT NULL,
    created_at              timestamp(6) with time zone,
    updated_at              timestamp(6) with time zone,
    CONSTRAINT fk_detail_folder_merges_gallery FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE,
    CONSTRAINT fk_detail_folder_merges_source FOREIGN KEY (source_detail_folder_id) REFERENCES detail_folders (id) ON DELETE CASCADE,
    CONSTRAINT fk_detail_folder_merges_target FOREIGN KEY (target_detail_folder_id) REFERENCES detail_folders (id) ON DELETE CASCADE,
    CONSTRAINT fk_detail_folder_merges_user FOREIGN KEY (merged_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);
-- 폴더 삭제의 CASCADE 가 두 FK 를 탄다.
CREATE INDEX idx_detail_folder_merges_source ON detail_folder_merges (source_detail_folder_id);
CREATE INDEX idx_detail_folder_merges_target ON detail_folder_merges (target_detail_folder_id);

CREATE TABLE detail_folder_merge_photos (
    merge_id            bigint                      NOT NULL,
    photo_id            bigint                      NOT NULL,
    assigned_by_user_id bigint,
    assigned_source     varchar(20)                 NOT NULL,
    confidence          double precision,
    assigned_at         timestamp(6) with time zone NOT NULL,
    PRIMARY KEY (merge_id, photo_id),
    CONSTRAINT ck_detail_folder_merge_photos_source CHECK (assigned_source IN ('AI', 'USER')),
    CONSTRAINT fk_detail_folder_merge_photos_merge FOREIGN KEY (merge_id) REFERENCES detail_folder_merges (id) ON DELETE CASCADE,
    CONSTRAINT fk_detail_folder_merge_photos_photo FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE
);
