-- 관리자 보정 산출물은 브라우저가 storage key를 직접 입력하지 않는다.
-- 발급 -> S3 PUT -> 존재 확인 -> 확정의 두 단계 계약으로만 현재 항목에 연결한다.
CREATE TABLE admin_retouch_artifact_uploads
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id           BIGINT                   NOT NULL,
    retouch_photo_id   BIGINT                   NOT NULL,
    artifact_type      VARCHAR(20)              NOT NULL,
    storage_key        VARCHAR(500)             NOT NULL,
    original_file_name VARCHAR(255)             NOT NULL,
    content_type       VARCHAR(100)             NOT NULL,
    status             VARCHAR(20)              NOT NULL,
    expires_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_admin_id     BIGINT,
    reason             VARCHAR(500)             NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_admin_retouch_artifact_upload_round
        FOREIGN KEY (round_id) REFERENCES retouch_rounds (id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_retouch_artifact_upload_photo
        FOREIGN KEY (retouch_photo_id) REFERENCES retouch_photos (id) ON DELETE CASCADE,
    CONSTRAINT uk_admin_retouch_artifact_storage_key UNIQUE (storage_key),
    CONSTRAINT ck_admin_retouch_artifact_type
        CHECK (artifact_type IN ('ANNOTATION', 'RESULT')),
    CONSTRAINT ck_admin_retouch_artifact_status
        CHECK (status IN ('PENDING', 'COMPLETED', 'EXPIRED'))
);

CREATE UNIQUE INDEX uk_admin_retouch_artifact_pending
    ON admin_retouch_artifact_uploads (retouch_photo_id, artifact_type)
    WHERE status = 'PENDING';

CREATE INDEX idx_admin_retouch_artifact_round
    ON admin_retouch_artifact_uploads (round_id, retouch_photo_id, created_at DESC);
