-- 사진마다 하나인 메모. 개인 갤러리 소유자와 파트너가 같은 한 칸을 함께 고치고 마지막에 쓴 사람이 updated_by에 남는다.
-- 작가에게 가는 보정 요청(retouch_photos.request_text)이나 부부 댓글(photo_comments)과는 별도 자원이다.
CREATE TABLE photo_memos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_photo_memos_photo_id UNIQUE (photo_id),
    CONSTRAINT fk_photo_memos_photo FOREIGN KEY (photo_id) REFERENCES photos(id) ON DELETE CASCADE,
    CONSTRAINT fk_photo_memos_user FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_photo_memos_content CHECK (char_length(btrim(content)) BETWEEN 1 AND 2000)
);

CREATE INDEX idx_photo_memos_updated_by ON photo_memos(updated_by);
