-- External email/SMS delivery is not an approved admin workflow. New manual notifications are
-- stored only in this shared super-admin inbox. The legacy outbox is left intact for an explicitly
-- approved historical-data cleanup migration, but application code no longer writes or claims it.

CREATE TABLE admin_notification_inbox
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type          VARCHAR(80)              NOT NULL,
    target_type         VARCHAR(40)              NOT NULL,
    target_id           BIGINT                   NOT NULL,
    work_status         VARCHAR(20)              NOT NULL,
    safe_summary        VARCHAR(240)             NOT NULL,
    correlation_id      VARCHAR(16),
    idempotency_key_hash VARCHAR(64)              NOT NULL,
    created_by_admin_id BIGINT,
    version             BIGINT                   NOT NULL DEFAULT 0,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_admin_notification_inbox_event_type CHECK (
        event_type IN (
            'PHOTO_REPLACED',
            'CUSTOMER_FOLLOW_UP',
            'PROCESSING_REVIEW',
            'CONTENT_REVIEW',
            'DELIVERY_REVIEW',
            'DATA_CORRECTION_REVIEW',
            'GENERAL_OPERATION_NOTICE'
        )
    ),
    CONSTRAINT ck_admin_notification_inbox_target_type CHECK (
        target_type IN (
            'USER', 'STUDIO', 'GALLERY', 'PHOTO', 'SELECTION',
            'COLLABORATION', 'ALBUM', 'RETOUCH_REQUEST'
        )
    ),
    CONSTRAINT ck_admin_notification_inbox_work_status
        CHECK (work_status IN ('OPEN', 'CANCELED')),
    CONSTRAINT ck_admin_notification_inbox_correlation
        CHECK (correlation_id IS NULL OR correlation_id ~ '^[0-9a-f]{16}$'),
    CONSTRAINT ck_admin_notification_inbox_idempotency_hash
        CHECK (idempotency_key_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT uk_admin_notification_inbox_idempotency UNIQUE (idempotency_key_hash),
    CONSTRAINT fk_admin_notification_inbox_creator
        FOREIGN KEY (created_by_admin_id) REFERENCES admin_accounts (id) ON DELETE SET NULL
);

CREATE INDEX idx_admin_notification_inbox_target
    ON admin_notification_inbox (target_type, target_id, created_at DESC, id DESC);
CREATE INDEX idx_admin_notification_inbox_created_at
    ON admin_notification_inbox (created_at DESC, id DESC);
CREATE INDEX idx_admin_notification_inbox_open
    ON admin_notification_inbox (work_status, created_at DESC, id DESC);

CREATE TABLE admin_notification_inbox_reads
(
    notification_id      BIGINT                   NOT NULL,
    admin_id             BIGINT                   NOT NULL,
    notification_version BIGINT                   NOT NULL,
    read_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (notification_id, admin_id),
    CONSTRAINT fk_admin_notification_inbox_reads_notification
        FOREIGN KEY (notification_id) REFERENCES admin_notification_inbox (id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_notification_inbox_reads_admin
        FOREIGN KEY (admin_id) REFERENCES admin_accounts (id) ON DELETE CASCADE,
    CONSTRAINT ck_admin_notification_inbox_read_version CHECK (notification_version >= 0)
);

CREATE INDEX idx_admin_notification_inbox_reads_admin
    ON admin_notification_inbox_reads (admin_id, read_at DESC);

COMMENT ON TABLE admin_notification_inbox IS
    '최고 관리자 전용 내부 알림. 외부 수신자와 원문 payload를 저장하거나 전송하지 않는다.';
COMMENT ON COLUMN admin_notification_inbox.safe_summary IS
    '서버 allowlist로 생성한 비식별 운영 요약. 운영자 자유문과 사용자 PII를 받지 않는다.';
COMMENT ON COLUMN admin_notification_inbox.idempotency_key_hash IS
    '호출자가 보낸 멱등 키 원문은 보관하지 않고 SHA-256 해시만 보관한다.';
COMMENT ON TABLE admin_notification_inbox_reads IS
    '관리자별 단조 읽음 영수증. 복합 PK가 반복 읽음 요청을 멱등 처리한다.';
