-- AI 폴더화(docs/plans/ai-folder-structure.md)의 저장소. 모델 파생값 테이블과 분석 잡·컨셉 배정
-- 테이블을 만들고, photos.embedding을 photo_analysis로 옮기고, 폴더에 AI 세트 표식을 단다.
--
-- photo_analysis를 photos에서 떼는 기준은 생명주기다. photos는 업로드 시 한 번 정해지는
-- 정체성(storage_key·EXIF)이고, 임베딩·그룹·점수·클러스터는 모델을 바꿀 때마다 갤러리 단위로
-- 통째 다시 적는 파생값이다. photos에 얹어 두면 목록 조회가 쓰지도 않는 768차원 벡터를 읽고
-- (photo_ratings와 같은 이유), 모델 교체가 정체성 행의 UPDATE가 된다.
--
-- 쓰는 주체가 둘이다. 임베더 Lambda가 embedding·embedding_model을 채우고(사진당 한 행을
-- INSERT ... ON CONFLICT), AI 분석 배치(full 잡)가 나머지를 채운다. 그래서 분석 컬럼은 NULL을
-- 허용하고, model_version이 있으면 분석 컬럼이 전부 있어야 한다는 것만 CHECK로 건다.
-- 추천 이유용 컬럼(scene/framing/lighting/expression/caption)은 만들지 않는다 —
-- 추천 기능은 재설계 대상이라 그때 별도 마이그레이션으로 온다.

CREATE TABLE photo_analysis
(
    photo_id        BIGINT PRIMARY KEY,
    -- 768은 DINOv3 ViT-B/16의 CLS 토큰 차원(DINOv2-base와 같다). PhotoAnalysis.EMBEDDING_DIMENSION·
    -- 인프라의 embedding_dimension과 세 곳이 일치해야 한다(.claude/rules/migration.md).
    embedding       vector(768),
    -- 벡터를 만든 모델 id(예: facebook/dinov3-vitb16-pretrain-lvd1689m). 모델이 바뀌면 이 값으로
    -- 재계산 대상을 가른다.
    embedding_model VARCHAR(60),
    -- CLIP ViT-L/14 벡터. 소그룹 최근접 배정과 부모 검증(naming 잡)이 쓴다 — 사진 재분석 없이
    -- naming 잡만 다시 돌리기 위해 저장한다.
    clip_embedding  vector(768),
    -- 임베딩 그룹(concat 계층 클러스터). 갤러리 안에서만 유일한 번호. -1 = 미배정(임베딩 없음).
    -- 화면에 나오지 않는 내부 단위다 — "누가 같은 세트인가"는 여기서 끝난다.
    embed_group_id  INTEGER,
    -- CLIP zero-shot 피사체(신부/신랑/두 분/단체). 자식 폴더의 category 재료.
    -- CHECK/enum을 걸지 않는 이유: 어휘 계약은 AI repo와 model_version이 지고, 어휘가 바뀔 때마다
    -- 마이그레이션이 필요해지면 안 된다.
    subjects        VARCHAR(20),
    -- 갤러리 안 백분위 0~100. 원점수가 아니다 — 모델마다 단위가 달라 갤러리 안 순위로 통일한다.
    technical_pct   REAL,
    aesthetic_pct   REAL,
    -- {face_count, max_face_ratio}. 얼굴 신호는 클러스터 대표 선정에만 쓴다.
    face_boxes      JSONB        NOT NULL DEFAULT '{}',
    -- 원점수 {technical_score, aesthetic_score, eyes_open, smile}. 모델이 바뀌면 키가 바뀐다.
    sub_scores      JSONB        NOT NULL DEFAULT '{}',
    -- 근접 중복(연사) 클러스터. 갤러리 안에서만 유일한 번호. 폴더 상세의 정렬 재료.
    cluster_id      INTEGER,
    -- 클러스터 안 순위. 0이 대표.
    cluster_rank    INTEGER,
    -- 분석 컬럼을 만든 파이프라인 버전. NULL이면 임베딩만 있고 분석은 아직이다.
    model_version   VARCHAR(40),
    analyzed_at     TIMESTAMP(6) WITH TIME ZONE,
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_photo_analysis_photo FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE,
    CONSTRAINT ck_photo_analysis_analyzed
        CHECK (
            model_version IS NULL
            OR (
                subjects IS NOT NULL
                AND technical_pct IS NOT NULL AND aesthetic_pct IS NOT NULL
                AND cluster_id IS NOT NULL AND cluster_rank IS NOT NULL
                AND embed_group_id IS NOT NULL
                AND analyzed_at IS NOT NULL
            )
        )
);
-- 갤러리 단위 조회는 photos.gallery_id로 조인한다. gallery_id를 여기 중복 저장하지 않는다.

-- 기존 벡터를 옮긴다. 지금까지의 벡터는 전부 임베더(DINOv2-base)가 만든 것이다.
INSERT INTO photo_analysis (photo_id, embedding, embedding_model, created_at, updated_at)
SELECT id, embedding, 'facebook/dinov2-base', now(), now()
FROM photos
WHERE embedding IS NOT NULL;

ALTER TABLE photos
    DROP COLUMN embedding;

-- 갤러리 전수 분석 잡. DB가 곧 큐다(별도 큐 서비스 없음).
-- wes가 PENDING으로 넣고, 분석 배치가 집어가 RUNNING -> DONE/FAILED로 옮긴다.
-- mode: 사진별 분석(full)과 이름·배정(naming)을 나눈다. 7000장에서 full은 30~40분, naming은
-- 1~2분 — VLM 실패나 작가 정의 컨셉 변경 때 naming만 다시 돈다. 진행률은 result.progress.
CREATE TABLE ai_analysis_jobs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id  BIGINT       NOT NULL,
    mode        VARCHAR(10)  NOT NULL DEFAULT 'FULL',
    -- PENDING / RUNNING / DONE / FAILED
    status      VARCHAR(20)  NOT NULL,
    started_at  TIMESTAMP(6) WITH TIME ZONE,
    finished_at TIMESTAMP(6) WITH TIME ZONE,
    error       TEXT,
    -- 처리 결과 요약 {targets, processed, failed, groups, progress: {processed, total}, ...}
    result      JSONB,
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_ai_analysis_jobs_gallery FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE,
    CONSTRAINT ck_ai_analysis_jobs_mode CHECK (mode IN ('FULL', 'NAMING')),
    CONSTRAINT ck_ai_analysis_jobs_status CHECK (status IN ('PENDING', 'RUNNING', 'DONE', 'FAILED'))
);
-- 갤러리당 살아 있는 잡은 하나. 부분 유니크라 DONE/FAILED 이력은 쌓인다.
CREATE UNIQUE INDEX uk_ai_analysis_jobs_active
    ON ai_analysis_jobs (gallery_id)
    WHERE status IN ('PENDING', 'RUNNING');

-- naming 잡이 남기는 컨셉 배정: 임베딩 그룹 → (큰 분류, 컨셉 이름). 잡 1회의 산출물이라 잡에
-- 매단다 — 같은 갤러리를 다시 돌리면 새 잡 밑에 새 배정이 쌓이고, 폴더 생성은 최신 DONE 잡의
-- 배정만 읽는다.
CREATE TABLE ai_concept_assignments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          BIGINT       NOT NULL REFERENCES ai_analysis_jobs (id) ON DELETE CASCADE,
    gallery_id      BIGINT       NOT NULL,
    embed_group_id  INTEGER      NOT NULL,
    -- 큰 분류('야외 자연') — 촬영 종류별 고정 목록 안의 값 또는 '기타'.
    parent_name     VARCHAR(100) NOT NULL,
    -- parent_name이 '기타'일 때 VLM이 제안한 이름. 고정 목록 확장의 근거로만 쓴다.
    proposed_parent VARCHAR(100),
    -- 컨셉 이름('해변'). VLM의 열린 답 또는 작가 정의 컨셉.
    concept_name    VARCHAR(100) NOT NULL,
    confidence      REAL         NOT NULL,
    -- CLIP zero-shot 다수결이 판정한 큰 분류. parent_name과 다르면 needs_review의 근거.
    clip_parent     VARCHAR(100),
    -- vlm(상위 K그룹, VLM이 직접) | nearest(K 밖 소그룹, 임베딩 최근접 상속)
    assigned_by     VARCHAR(10)  NOT NULL,
    needs_review    BOOLEAN      NOT NULL DEFAULT FALSE,
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_ai_concept_assignments_job_group UNIQUE (job_id, embed_group_id),
    CONSTRAINT ck_ai_concept_assignments_assigned_by CHECK (assigned_by IN ('vlm', 'nearest'))
);
CREATE INDEX idx_ai_concept_assignments_gallery_id ON ai_concept_assignments (gallery_id);

-- 촬영 종류. 큰 분류(부모) 고정 목록을 고르는 키. 기존 갤러리는 전부 리허설 촬영이었다.
ALTER TABLE galleries
    ADD COLUMN shoot_type VARCHAR(20) NOT NULL DEFAULT 'REHEARSAL';
ALTER TABLE galleries
    ADD CONSTRAINT ck_galleries_shoot_type CHECK (shoot_type IN ('REHEARSAL', 'CEREMONY', 'OTHER'));

-- 폴더에 AI 세트 표식을 단다. 한 번의 POST /folder-groups/ai가 만든 부모들은 analysis_job_id가
-- 같은 한 세트다 — 프론트가 세트 단위로 보여 주거나 지우고, 추천이 기준 세트를 고른다.
ALTER TABLE photo_folder_groups
    ADD COLUMN origin VARCHAR(20) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE photo_folder_groups
    ADD CONSTRAINT ck_photo_folder_groups_origin CHECK (origin IN ('MANUAL', 'AI'));
ALTER TABLE photo_folder_groups
    ADD COLUMN analysis_job_id BIGINT REFERENCES ai_analysis_jobs (id) ON DELETE SET NULL;

-- 자식 폴더의 피사체 카테고리(subjects 과반)와 확인 필요 표식. 확인은 사용자가 폴더를 검토하고
-- 끄는 값이라 서버가 다시 켜지 않는다.
ALTER TABLE photo_folders
    ADD COLUMN category VARCHAR(20);
ALTER TABLE photo_folders
    ADD COLUMN needs_review BOOLEAN NOT NULL DEFAULT FALSE;

-- 운영 DB에 embedder 전용 role이 이미 있으면 워커가 쓰는 권한 전체를 다시 연다(V42의 전례).
-- photo_analysis만 추가하지 않고 전체를 다시 적는 이유: photos.embedding DROP으로 V42의 컬럼
-- GRANT 일부가 사라졌고, 이 블록이 "현재 워커 권한 계약"의 단일 출처가 되어야
-- AdminEmbedderPrivilegeContractTest가 이 블록 하나로 검증할 수 있다. 재GRANT는 멱등이다.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'embedder') THEN
        EXECUTE 'GRANT SELECT (id, deleted_at) ON galleries TO embedder';
        EXECUTE 'GRANT SELECT (id, gallery_id, storage_key, status, deleted_at, preview_key, '
                'taken_at, camera_make, camera_model, exposure_time, f_number, iso, width, height, '
                'byte_size, version) ON photos TO embedder';
        EXECUTE 'GRANT UPDATE (status, preview_key, taken_at, camera_make, camera_model, '
                'exposure_time, f_number, iso, width, height, byte_size, technical_quality_score, '
                'technical_quality_signals, quality_analyzed_at, version, updated_at) ON photos TO embedder';
        EXECUTE 'GRANT SELECT, INSERT, UPDATE ON photo_analysis TO embedder';
        EXECUTE 'GRANT SELECT (id, attempt_count, job_type, target_type, target_id, revision_id, status, payload) '
                'ON admin_processing_jobs TO embedder';
        EXECUTE 'GRANT UPDATE (status, failure_code, last_run_at, updated_at) '
                'ON admin_processing_jobs TO embedder';
        EXECUTE 'GRANT SELECT (id, photo_id, storage_key) ON admin_photo_revisions TO embedder';
    END IF;
END
$$;
