-- 폴더별 AI 추천(AI repo photoselect/docs/plan-v3-folder-compare.md 기능 1)의 저장소.
-- 추천 잡 큐와 추천 행을 만든다. V45의 ai_analysis_jobs와 같은 규약이다 — 이 서버는 PENDING을
-- 넣기까지만 하고, AI 워커(photoselect)가 집어가 상태를 전이하며 추천 행을 직접 쓴다.
--
-- 추천 계산은 전부 워커 몫이다: 폴더마다 n_f = max(1, round(남은 목표 × |폴더| / 전체)) 장을
-- (폴더 절반 상한) 점수순으로 고르고, 이유 문장은 2단계로 나중에 UPDATE 한다(reason NULL 허용).
-- 목표 장수는 galleries.max_selectable_photo_count 를 워커가 읽는다.

-- 추천 잡. DB가 곧 큐다 — wes가 PENDING으로 넣고 워커가 RUNNING -> DONE/FAILED 로 옮긴다.
-- mode 는 AI repo 계약대로 소문자다(잡을 집은 워커가 draft=round 1, refine=다음 라운드로 분기).
CREATE TABLE ai_selection_jobs
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selection_id      BIGINT       NOT NULL REFERENCES photo_selections (id) ON DELETE CASCADE,
    -- draft(첫 라운드) / refine(담기·거절 반응을 반영한 다음 라운드)
    mode              VARCHAR(10)  NOT NULL DEFAULT 'draft',
    -- PENDING / RUNNING / DONE / FAILED
    status            VARCHAR(20)  NOT NULL,
    -- 어느 AI 폴더 세트를 기준으로 요청했는지(ai_analysis_jobs.id = photo_folder_groups.analysis_job_id).
    -- 프론트가 현재 보는 세트와 다르면 "추천을 다시 받으세요"를 띄우는 재현용 값이다.
    folder_set_job_id BIGINT REFERENCES ai_analysis_jobs (id) ON DELETE SET NULL,
    -- 워커가 이 잡으로 만든 추천 라운드 번호. 끝나기 전에는 NULL.
    round             INTEGER,
    started_at        TIMESTAMP(6) WITH TIME ZONE,
    finished_at       TIMESTAMP(6) WITH TIME ZONE,
    error             TEXT,
    -- 처리 결과 요약 {round, selected, target, remaining, perFolder, ...}
    result            JSONB,
    version           BIGINT       NOT NULL DEFAULT 0,
    created_at        TIMESTAMP(6) WITH TIME ZONE,
    updated_at        TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT ck_ai_selection_jobs_mode CHECK (mode IN ('draft', 'refine')),
    CONSTRAINT ck_ai_selection_jobs_status CHECK (status IN ('PENDING', 'RUNNING', 'DONE', 'FAILED'))
);
-- 셀렉당 살아 있는 잡은 하나. 부분 유니크라 DONE/FAILED 이력은 쌓인다.
CREATE UNIQUE INDEX uk_ai_selection_jobs_active
    ON ai_selection_jobs (selection_id)
    WHERE status IN ('PENDING', 'RUNNING');

-- AI가 한 셀렉에 제시한 사진 한 장. 라운드마다 쌓이고(이력), 화면은 최신 라운드만 읽는다 —
-- refine이 이전 라운드를 덮어쓰는 대신 새 라운드를 통째로 다시 적기 때문에, 같은 사진이
-- 여러 라운드에 나올 수 있다(UNIQUE 에 round 가 들어가는 이유).
CREATE TABLE ai_recommendations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selection_id    BIGINT       NOT NULL REFERENCES photo_selections (id) ON DELETE CASCADE,
    photo_id        BIGINT       NOT NULL REFERENCES photos (id) ON DELETE CASCADE,
    round           INTEGER      NOT NULL,
    -- 폴더 안 순위. 1이 그 폴더의 대표다.
    rank            INTEGER      NOT NULL,
    -- 추천 당시의 자식 폴더. 세트에 안 들어간 사진(미분류 가상 폴더)은 NULL. 재현용이다 —
    -- 폴더 화면은 현재 photo_folder_items 조인으로 그리므로, 사용자가 사진을 옮겨도 안 깨진다.
    folder_id       BIGINT REFERENCES photo_folders (id) ON DELETE SET NULL,
    -- 순위의 근거 원자료 {prior, tech_pct, aes_pct, balance_z, ...}. 워커만 쓰고 이 서버는 읽지 않는다.
    score_breakdown JSONB        NOT NULL DEFAULT '{}',
    -- 이유 문장. 2단계라 추천 행이 먼저 생기고(NULL) LLM 문장이 뒤이어 UPDATE 된다 —
    -- 프론트는 NULL 이면 "이유 준비 중"을 그린다.
    reason          TEXT,
    presented_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- 부부의 반응. 워커의 refine 이 rejected_at 을 제외 조건으로 읽는다.
    -- 반응을 남기는 wes API는 다음 이슈다 — 계약(컬럼)만 먼저 둔다.
    accepted_at     TIMESTAMP(6) WITH TIME ZONE,
    rejected_at     TIMESTAMP(6) WITH TIME ZONE,
    -- 담았다가 뺀 시각. "전체 담기" 부풀림을 잡는 후회율의 재료다.
    unselected_at   TIMESTAMP(6) WITH TIME ZONE,
    accept_mode     VARCHAR(10),
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_ai_recommendations_selection_round_photo UNIQUE (selection_id, round, photo_id),
    CONSTRAINT ck_ai_recommendations_accept_mode CHECK (accept_mode IS NULL OR accept_mode IN ('single', 'bulk'))
);
CREATE INDEX idx_ai_recommendations_selection_round ON ai_recommendations (selection_id, round);

-- 운영 DB에 AI 워커 전용 role(photoselect)이 이미 있으면 워커가 쓰는 권한 전체를 연다.
-- V45의 embedder 블록과 같은 규약: 이 블록이 "현재 photoselect 권한 계약"의 단일 출처다.
-- photo_ratings 는 일부러 없다 — 사람의 별점을 추천 입력으로 쓰지 않는다(AI repo 계약).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'photoselect') THEN
        EXECUTE 'GRANT SELECT ON galleries, photos, photo_analysis, '
                'photo_folder_groups, photo_folders, photo_folder_items, '
                'photo_selections, photo_selection_items, '
                'ai_analysis_jobs, ai_concept_assignments, ai_selection_jobs, ai_recommendations '
                'TO photoselect';
        EXECUTE 'GRANT INSERT, UPDATE ON photo_analysis, ai_concept_assignments, ai_recommendations TO photoselect';
        EXECUTE 'GRANT UPDATE ON ai_analysis_jobs, ai_selection_jobs TO photoselect';
    END IF;
END
$$;
