-- 비교샷 AI 판정(AI repo photoselect/docs/plan-v3-folder-compare.md 기능 2)의 저장소.
-- 두 사진 중 AI가 고른 것과 그 이유를 담는다. 쓰는 주체는 AI 쪽(compare — Lambda RequestResponse
-- 또는 로컬 서브프로세스)이고, wes는 동기 API로 그 실행을 시작시켜 응답을 그대로 돌려준다.
--
-- 사람의 답(pair_comparison_events)과 절대 같은 테이블에 섞지 않는다 — "누가 골랐나"가 흐려지면
-- 사람 답을 AI 판정의 평가 데이터로 쓸 수 없다.
CREATE TABLE ai_pair_verdicts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selection_id    BIGINT       NOT NULL REFERENCES photo_selections (id) ON DELETE CASCADE,
    photo_a         BIGINT       NOT NULL REFERENCES photos (id) ON DELETE CASCADE,
    photo_b         BIGINT       NOT NULL REFERENCES photos (id) ON DELETE CASCADE,
    chosen_photo_id BIGINT       NOT NULL,
    -- clear(뚜렷한 차이) | slight(거의 같아요, 굳이 고르면). 항상 하나는 고른다.
    confidence      VARCHAR(10)  NOT NULL,
    reason          TEXT         NOT NULL,
    -- 재현용 사실 목록(초점 비, 백분위 차, 연사 관계, 폴더, 담김 여부 ...). AI만 쓴다.
    facts           JSONB        NOT NULL,
    -- 모델 id + 프롬프트 버전. 세대가 바뀌면 캐시 미스가 되어 같은 쌍을 다시 판정해 덮는다.
    model_version   VARCHAR(50)  NOT NULL,
    -- llm(사진을 본 판정) | template(타임아웃·실패 시 수치만으로). UI가 문구 톤을 가른다.
    source          VARCHAR(10)  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT ck_ai_pair_verdicts_chosen CHECK (chosen_photo_id IN (photo_a, photo_b)),
    CONSTRAINT ck_ai_pair_verdicts_confidence CHECK (confidence IN ('clear', 'slight')),
    CONSTRAINT ck_ai_pair_verdicts_source CHECK (source IN ('llm', 'template'))
);
-- 순서 무관 캐시 — (a, b)와 (b, a)는 같은 판정 한 행이다. 식 인덱스인 이유: 테이블 UNIQUE 제약은
-- 식을 못 받는다. AI의 저장이 이 인덱스를 ON CONFLICT 대상으로 쓰므로 식이 한 글자도 다르면 안 된다
-- (photoselect v3/store.py write_pair_verdict).
CREATE UNIQUE INDEX uk_ai_pair_verdicts_selection_pair
    ON ai_pair_verdicts (selection_id, LEAST(photo_a, photo_b), GREATEST(photo_a, photo_b));

-- AI 워커 전용 role이 이미 있으면 판정 테이블 권한을 연다(V46의 photoselect 블록에 추가되는 계약).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'photoselect') THEN
        EXECUTE 'GRANT SELECT, INSERT, UPDATE ON ai_pair_verdicts TO photoselect';
    END IF;
END
$$;
