-- 예비 부부가 클러스터 결과에 이름을 붙여 확정한 사진 묶음.
--
-- 임계값과 클러스터 식별자만 저장하지 않는 이유: 클러스터는 임계값이 바뀌면 다른 모양이 되고,
-- 사진이 더 올라와도 달라진다. 그런 값으로는 사용자가 "이 폴더"라고 부른 것을 다시 만들어낼 수
-- 없다. 폴더는 클러스터를 가리키는 포인터가 아니라 그 시점의 목록을 고정한 스냅샷이다.
-- 그래서 임계값 컬럼도 두지 않는다 -- 만들어진 뒤로는 아무 의미가 없다.
CREATE TABLE photo_folders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id BIGINT       NOT NULL,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE
);

-- 폴더 목록은 항상 갤러리 단위로 읽는다.
CREATE INDEX idx_photo_folders_gallery_id ON photo_folders (gallery_id);

-- 이름에 유니크를 걸지 않는다. 갤러리 하나를 신랑과 신부가 함께 쓰므로 같은 이름이 두 번
-- 나올 수 있고, 그때 막아서 얻는 것보다 "이미 있는 이름입니다"로 막히는 쪽이 성가시다.

CREATE TABLE photo_folder_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id  BIGINT NOT NULL,
    photo_id   BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    -- 같은 사진을 두 번 넣는 것은 사용자의 의도가 아니라 중복 요청이다. 애플리케이션에서도
    -- 거르지만, 동시에 두 번 눌린 요청은 거기서 새므로 DB가 마지막으로 막는다.
    -- 폴더 하나를 여는 질의(folder_id 단독)도 이 제약이 만드는 인덱스가 받는다.
    -- 선두 컬럼이 folder_id라서, 따로 인덱스를 더 두면 쓰기 비용만 늘고 얻는 것이 없다.
    CONSTRAINT uk_photo_folder_items_folder_id_photo_id UNIQUE (folder_id, photo_id)
);
