-- Product policy expansion.
-- V1~V4 are already deployed. This migration is additive and keeps every legacy
-- column required by the V4 application so the public API can be rolled back.

-- The album-composition folder domain was removed by V2. Recreate it without
-- conflating it with category folders. V2 deleted any rows that existed before
-- deployment; this migration preserves all data created from this point onward.
CREATE TABLE IF NOT EXISTS public.admin_album_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL,
    layout_json jsonb NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    studio_id bigint
);

CREATE INDEX IF NOT EXISTS idx_admin_album_templates_active
    ON public.admin_album_templates (deleted_at, name);
CREATE INDEX IF NOT EXISTS idx_admin_album_templates_studio
    ON public.admin_album_templates (studio_id, id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_admin_album_templates_studio_name
    ON public.admin_album_templates (studio_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS uk_admin_album_templates_active_name
    ON public.admin_album_templates (name) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.photo_folder_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    version bigint DEFAULT 0 NOT NULL,
    deleted_at timestamp with time zone,
    selection_revision_id bigint,
    template_name character varying(100),
    template_id bigint,
    CONSTRAINT fk_photo_folder_groups_gallery FOREIGN KEY (gallery_id)
        REFERENCES public.galleries(id) ON DELETE CASCADE,
    CONSTRAINT fk_photo_folder_groups_admin_template FOREIGN KEY (template_id)
        REFERENCES public.admin_album_templates(id) ON DELETE SET NULL,
    CONSTRAINT fk_photo_folder_groups_selection_revision FOREIGN KEY (selection_revision_id)
        REFERENCES public.admin_selection_revisions(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_photo_folder_groups_gallery_id
    ON public.photo_folder_groups (gallery_id);
CREATE INDEX IF NOT EXISTS idx_photo_folder_groups_deleted_at
    ON public.photo_folder_groups (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.photo_folders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint NOT NULL,
    gallery_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT fk_photo_folders_group FOREIGN KEY (group_id)
        REFERENCES public.photo_folder_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_photo_folders_gallery FOREIGN KEY (gallery_id)
        REFERENCES public.galleries(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_photo_folders_group_id ON public.photo_folders (group_id);
CREATE INDEX IF NOT EXISTS idx_photo_folders_gallery_id ON public.photo_folders (gallery_id);

CREATE TABLE IF NOT EXISTS public.photo_folder_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint NOT NULL,
    folder_id bigint NOT NULL,
    photo_id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    version bigint DEFAULT 0 NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    crop_json jsonb,
    CONSTRAINT fk_photo_folder_items_group FOREIGN KEY (group_id)
        REFERENCES public.photo_folder_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_photo_folder_items_folder FOREIGN KEY (folder_id)
        REFERENCES public.photo_folders(id) ON DELETE CASCADE,
    CONSTRAINT fk_photo_folder_items_photo FOREIGN KEY (photo_id)
        REFERENCES public.photos(id) ON DELETE CASCADE,
    CONSTRAINT uk_photo_folder_items_group_id_photo_id UNIQUE (group_id, photo_id)
);
CREATE INDEX IF NOT EXISTS idx_photo_folder_items_folder_id ON public.photo_folder_items (folder_id);

-- Restore admin resource values removed together with the album tables.
ALTER TABLE public.admin_child_trash_records DROP CONSTRAINT IF EXISTS ck_admin_child_trash_resource_parent;
ALTER TABLE public.admin_child_trash_records ADD CONSTRAINT ck_admin_child_trash_resource_parent CHECK (
    (resource_type = 'COLLAB_COMMENT' AND parent_type = 'COLLABORATION')
    OR (resource_type = 'COLLAB_LIKE' AND parent_type = 'COLLABORATION')
    OR (resource_type = 'ALBUM_TEMPLATE' AND parent_type = 'ALBUM')
    OR (resource_type = 'RETOUCH_ITEM' AND parent_type = 'RETOUCH_REQUEST')
);

ALTER TABLE public.admin_notification_inbox DROP CONSTRAINT IF EXISTS ck_admin_notification_inbox_target_type;
ALTER TABLE public.admin_notification_inbox ADD CONSTRAINT ck_admin_notification_inbox_target_type CHECK (
    target_type IN (
        'USER', 'WORKSPACE', 'STUDIO', 'GALLERY', 'PHOTO',
        'CONCEPT_FOLDER', 'DETAIL_FOLDER', 'PHOTO_CATEGORY_ASSIGNMENT', 'CATEGORIZATION_JOB',
        'PHOTO_RATING', 'SELECTION', 'COLLABORATION', 'ALBUM', 'RETOUCH_REQUEST'
    )
);

ALTER TABLE public.admin_processing_jobs DROP CONSTRAINT IF EXISTS ck_admin_processing_job_type;
ALTER TABLE public.admin_processing_jobs ADD CONSTRAINT ck_admin_processing_job_type CHECK (
    job_type IN ('DERIVATIVE', 'EMBEDDING', 'QUALITY_ANALYSIS', 'MOCK_RECALCULATION')
);

-- Gallery-owned category and selection references. Keep these nullable until
-- the validation gate in the contract migration.
ALTER TABLE public.detail_folders ADD COLUMN IF NOT EXISTS gallery_id bigint;
UPDATE public.detail_folders detail
SET gallery_id = concept.gallery_id
FROM public.concept_folders concept
WHERE detail.concept_folder_id = concept.id AND detail.gallery_id IS NULL;

ALTER TABLE public.photo_category_assignments ADD COLUMN IF NOT EXISTS gallery_id bigint;
UPDATE public.photo_category_assignments assignment
SET gallery_id = detail.gallery_id
FROM public.detail_folders detail
WHERE assignment.detail_folder_id = detail.id AND assignment.gallery_id IS NULL;

ALTER TABLE public.categorization_job_photos
    ADD COLUMN IF NOT EXISTS gallery_id bigint,
    ADD COLUMN IF NOT EXISTS status character varying(20) DEFAULT 'PENDING',
    ADD COLUMN IF NOT EXISTS failure_code character varying(80),
    ADD COLUMN IF NOT EXISTS processed_at timestamp with time zone;
UPDATE public.categorization_job_photos item
SET gallery_id = job.gallery_id,
    status = CASE
        WHEN item.status IS NOT NULL AND item.status <> 'PENDING' THEN item.status
        WHEN job.status = 'FAILED' THEN 'FAILED'
        WHEN EXISTS (
            SELECT 1 FROM public.photo_category_assignments assignment
            WHERE assignment.photo_id = item.photo_id AND assignment.gallery_id = job.gallery_id
        ) THEN 'ASSIGNED'
        WHEN job.status = 'SUCCEEDED' THEN 'UNCLASSIFIED'
        ELSE 'PENDING'
    END,
    failure_code = CASE WHEN job.status = 'FAILED' THEN job.failure_code ELSE item.failure_code END,
    processed_at = CASE WHEN job.status <> 'RUNNING' THEN COALESCE(job.completed_at, CURRENT_TIMESTAMP) ELSE item.processed_at END
FROM public.categorization_jobs job
WHERE item.job_id = job.id AND item.gallery_id IS NULL;

ALTER TABLE public.photo_selection_items
    ADD COLUMN IF NOT EXISTS gallery_id bigint,
    ADD COLUMN IF NOT EXISTS added_by_user_id bigint,
    ADD COLUMN IF NOT EXISTS sort_order integer;
UPDATE public.photo_selection_items item
SET gallery_id = selection.gallery_id
FROM public.photo_selections selection
WHERE item.selection_id = selection.id AND item.gallery_id IS NULL;
UPDATE public.photo_selection_items item
SET added_by_user_id = COALESCE(
        gallery.created_by_user_id,
        (SELECT member.user_id
         FROM public.workspace_members member
         WHERE member.workspace_id = gallery.workspace_id
           AND member.role = 'OWNER' AND member.deleted_at IS NULL
         ORDER BY member.id LIMIT 1)
    )
FROM public.photo_selections selection
JOIN public.galleries gallery ON gallery.id = selection.gallery_id
WHERE item.selection_id = selection.id AND item.added_by_user_id IS NULL;
WITH ordered AS (
    SELECT id, ROW_NUMBER() OVER (PARTITION BY selection_id ORDER BY created_at NULLS LAST, id) - 1 AS next_order
    FROM public.photo_selection_items
)
UPDATE public.photo_selection_items item
SET sort_order = ordered.next_order
FROM ordered
WHERE item.id = ordered.id AND item.sort_order IS NULL;

INSERT INTO public.photo_selections
    (gallery_id, status, version, created_at, updated_at)
SELECT gallery.id, 'SELECTING', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM public.galleries gallery
WHERE gallery.deleted_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM public.photo_selections selection WHERE selection.gallery_id = gallery.id)
ON CONFLICT (gallery_id) DO NOTHING;

ALTER TABLE public.categorization_job_photos
    DROP CONSTRAINT IF EXISTS ck_categorization_job_photos_status;
ALTER TABLE public.categorization_job_photos
    ADD CONSTRAINT ck_categorization_job_photos_status
    CHECK (status IN ('PENDING', 'ASSIGNED', 'UNCLASSIFIED', 'FAILED'));

ALTER TABLE public.galleries ADD CONSTRAINT uk_galleries_gallery_id_id UNIQUE (id, workspace_id);
ALTER TABLE public.photos ADD CONSTRAINT uk_photos_gallery_id_id UNIQUE (gallery_id, id);
ALTER TABLE public.concept_folders ADD CONSTRAINT uk_concept_folders_gallery_id_id UNIQUE (gallery_id, id);
ALTER TABLE public.detail_folders ADD CONSTRAINT uk_detail_folders_gallery_id_id UNIQUE (gallery_id, id);
ALTER TABLE public.categorization_jobs ADD CONSTRAINT uk_categorization_jobs_gallery_id_id UNIQUE (gallery_id, id);
ALTER TABLE public.photo_selections ADD CONSTRAINT uk_photo_selections_gallery_id_id UNIQUE (gallery_id, id);

CREATE INDEX IF NOT EXISTS idx_detail_folders_gallery ON public.detail_folders (gallery_id, id);
CREATE INDEX IF NOT EXISTS idx_photo_category_assignments_gallery ON public.photo_category_assignments (gallery_id, photo_id);
CREATE INDEX IF NOT EXISTS idx_categorization_job_photos_gallery ON public.categorization_job_photos (gallery_id, job_id);
CREATE INDEX IF NOT EXISTS idx_photo_selection_items_gallery ON public.photo_selection_items (gallery_id, selection_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_photo_selection_items_selection_sort_order
    ON public.photo_selection_items (selection_id, sort_order) WHERE sort_order IS NOT NULL;

-- Unified collaboration identity. The legacy guest table and foreign-key
-- columns remain for the V4/V5 rollback window.
CREATE TABLE IF NOT EXISTS public.collab_participants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collab_session_id bigint NOT NULL,
    participant_type character varying(20) NOT NULL,
    user_id bigint,
    guest_token character varying(255),
    nickname character varying(50) NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT ck_collab_participants_type CHECK (participant_type IN ('USER', 'GUEST')),
    CONSTRAINT ck_collab_participants_identity CHECK (
        (participant_type = 'USER' AND user_id IS NOT NULL AND guest_token IS NULL)
        OR (participant_type = 'GUEST' AND user_id IS NULL AND guest_token IS NOT NULL)
    ),
    CONSTRAINT fk_collab_participants_session FOREIGN KEY (collab_session_id)
        REFERENCES public.collab_sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_collab_participants_user FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_collab_participants_guest_token
    ON public.collab_participants (guest_token) WHERE guest_token IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_collab_participants_session_user
    ON public.collab_participants (collab_session_id, user_id)
    WHERE participant_type = 'USER' AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_collab_participants_session
    ON public.collab_participants (collab_session_id, id);

INSERT INTO public.collab_participants
    (collab_session_id, participant_type, user_id, guest_token, nickname, version, created_at, updated_at)
SELECT guest.collab_session_id, 'GUEST', NULL, guest.guest_token, guest.nickname,
       guest.version, guest.created_at, guest.updated_at
FROM public.collab_guests guest
ON CONFLICT (guest_token) WHERE guest_token IS NOT NULL DO NOTHING;

ALTER TABLE public.collab_photo_comments ADD COLUMN IF NOT EXISTS participant_id bigint;
ALTER TABLE public.collab_photo_likes ADD COLUMN IF NOT EXISTS participant_id bigint;
UPDATE public.collab_photo_comments comment
SET participant_id = participant.id
FROM public.collab_guests guest
JOIN public.collab_participants participant
  ON participant.guest_token = guest.guest_token
WHERE comment.collab_guest_id = guest.id AND comment.participant_id IS NULL;
UPDATE public.collab_photo_likes like_row
SET participant_id = participant.id
FROM public.collab_guests guest
JOIN public.collab_participants participant
  ON participant.guest_token = guest.guest_token
WHERE like_row.collab_guest_id = guest.id AND like_row.participant_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_collab_photo_comments_participant
    ON public.collab_photo_comments (participant_id, id);
CREATE INDEX IF NOT EXISTS idx_collab_photo_likes_participant
    ON public.collab_photo_likes (participant_id, id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_collab_photo_likes_active_session_photo_participant
    ON public.collab_photo_likes (collab_session_id, photo_id, participant_id)
    WHERE deleted_at IS NULL AND participant_id IS NOT NULL;
