-- 예비 부부가 최종적으로 고른 사진을 담는 선택 앨범.
--
-- photo_folders와 별개다. 폴더는 비슷한 사진을 묶어 이름 붙이는 중간 정리 도구라 여러 개를
-- 만들었다 지웠다 하지만, 선택 앨범은 작가에게 넘길 최종 목록이고 갤러리당 하나이며 제출되면
-- 잠긴다. 폴더에 "최종" 플래그를 다는 쪽이 테이블은 적었겠지만, 그러면 "여러 개 중 하나만
-- 최종"이라는 규칙을 애플리케이션이 매번 지켜야 하고 두 개가 최종이 된 순간을 DB는 모른다.

-- 계약 장수. 작가가 갤러리에 정하고 부부는 바꿀 수 없다.
--
-- 앨범이 아니라 갤러리에 두는 이유: 이 값은 계약에서 나오지 선택 과정에서 나오지 않는다.
-- 앨범이 사본을 들고 있으면 작가가 장수를 고친 뒤에도 앨범은 옛 값으로 막거나 열어준다.
--
-- NULL은 "제한 없음"이다. 장수를 정하지 않고 진행하는 계약도 있고, 이미 있는 갤러리에는
-- 넣어줄 값이 없다.
ALTER TABLE galleries
    ADD COLUMN target_photo_count INTEGER;

CREATE TABLE photo_selections
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id   BIGINT      NOT NULL,
    -- SELECTING / SUBMITTED. 제출 뒤에는 부부가 바꿀 수 없고 작가만 되돌린다.
    status       VARCHAR(20) NOT NULL,
    -- 제출 시각. 되돌리면 다시 NULL이 된다 -- 지금 제출된 상태인지가 status와 함께
    -- 한 방향을 가리켜야 해서, 되돌린 흔적을 여기에 남기지 않는다.
    submitted_at TIMESTAMP(6) WITH TIME ZONE,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    -- 갤러리당 하나. 애플리케이션은 갤러리 행을 잠그고 "없으면 만든다"를 하지만,
    -- 잠금을 빠뜨린 경로가 나중에 생기면 앨범이 둘이 되고 그때는 어느 쪽이 제출된 것인지
    -- 알 수 없다. DB가 마지막으로 막는다.
    CONSTRAINT uk_photo_selections_gallery_id UNIQUE (gallery_id)
);

CREATE TABLE photo_selection_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selection_id BIGINT NOT NULL,
    photo_id     BIGINT NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    -- 같은 사진을 두 번 넣는 것은 사용자의 의도가 아니라 중복 요청이다. 신랑과 신부가 같은
    -- 사진을 동시에 담는 일이 실제로 일어나고, 그때 행이 두 벌 쌓이면 목표 장수 계산이
    -- 조용히 틀어진다. 앨범 하나를 여는 질의(selection_id 단독)도 이 제약이 만드는 인덱스가
    -- 받는다 -- 선두 컬럼이 selection_id라서 따로 인덱스를 두면 쓰기 비용만 늘어난다.
    CONSTRAINT uk_photo_selection_items_selection_id_photo_id UNIQUE (selection_id, photo_id)
);
