-- 사진 한 장에 매기는 1~5점의 선호 별점.
--
-- **사진당 한 행이다.** 예비 부부 두 사람은 같이 고르는 한 팀이라 각자의 점수를 따로 모아
-- 평균을 내는 것이 화면에서 의미가 없고, 작가도 추천작을 같은 자리에 표시한다. 그래서
-- photo_id에 유니크를 걸고 마지막에 매긴 사람이 덮어쓴다. 누가 마지막이었는지는 rated_by에
-- 남지만 그것으로 거르지는 않는다 -- "부부가 5점 준 사진"과 "작가가 5점 준 사진"을 갈라
-- 봐야 할 날이 오면 유니크에 축을 하나 더하는 변경이 된다.
--
-- photos에 컬럼을 붙이지 않은 이유: 댓글·좋아요처럼 "사진에 사람이 남기는 것"은 계속 늘어난다.
-- 그때마다 photos가 넓어지면 수천 장을 훑는 목록 조회가 쓰지도 않는 컬럼을 함께 읽는다.
CREATE TABLE photo_ratings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_id   BIGINT  NOT NULL,
    score      INTEGER NOT NULL,
    -- 마지막으로 점수를 매긴 사람. 감사용이라 조회 조건으로 쓰지 않는다.
    rated_by   BIGINT  NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    -- 점수는 애플리케이션(PhotoRating.of/rate)이 먼저 막지만, 그 검증은 그 두 문을 지날 때만
    -- 돈다. 나중에 배치나 마이그레이션이 직접 UPDATE 하는 날 6점짜리 별이 화면에 뜬다.
    CONSTRAINT ck_photo_ratings_score CHECK (score BETWEEN 1 AND 5),
    -- 사진당 하나. 신랑과 신부가 같은 사진에 동시에 별을 달면 애플리케이션은 둘 다 "아직
    -- 없다"를 읽는데, 그 경합은 사진 행을 잠가 막고 여기가 마지막 방어선이다.
    CONSTRAINT uk_photo_ratings_photo_id UNIQUE (photo_id)
);
