-- 부부의 내부 대화는 공유 세션/게스트 댓글과 독립적으로 보관한다.
-- 갤러리·사진 휴지통에서는 부모 조회가 막고, 복원 시 대화도 다시 보인다.
CREATE TABLE photo_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content VARCHAR(500) NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_photo_comments_photo FOREIGN KEY (photo_id) REFERENCES photos(id) ON DELETE CASCADE,
    CONSTRAINT fk_photo_comments_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_photo_comments_content CHECK (char_length(btrim(content)) BETWEEN 1 AND 500)
);

CREATE INDEX idx_photo_comments_photo_id_id ON photo_comments(photo_id, id);
CREATE INDEX idx_photo_comments_author_id ON photo_comments(author_id);
