CREATE TABLE public.studio_invites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    token varchar(255) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    used_count integer NOT NULL DEFAULT 0 CHECK (used_count >= 0),
    version bigint NOT NULL DEFAULT 0,
    created_at timestamptz,
    updated_at timestamptz
);
CREATE UNIQUE INDEX uk_studio_invites_active_workspace ON public.studio_invites(workspace_id) WHERE revoked_at IS NULL;
ALTER TABLE public.user_notifications DROP CONSTRAINT ck_user_notifications_type;
ALTER TABLE public.user_notifications ADD CONSTRAINT ck_user_notifications_type CHECK (
    type IN ('WORKSPACE_DELETED', 'WORKSPACE_MEMBER_LEFT', 'GALLERY_MEMBER_LEFT', 'MEMBERSHIP_REMOVED',
             'SELECTION_SUBMITTED', 'RETOUCH_REQUESTED', 'RETOUCH_COMPLETED', 'INVITE_ACCEPTED', 'RETOUCH_CONFIRMED', 'SELECTION_REOPENED', 'GALLERY_OPENED', 'GALLERY_REOPENED', 'SELECTION_INCREASE_REQUESTED', 'SELECTION_INCREASE_APPROVED', 'PLAN_EXPIRED', 'DEADLINE_REMINDER', 'PLAN_EXPIRY_REMINDER', 'ANALYSIS_COMPLETED')
);
