-- 운영자 승인 뒤 스튜디오를 지울 때 하위 메타데이터가 남지 않도록 DB가 경계를 보장한다.
--
-- 기존 스키마에는 엔티티 간 외래키가 없었다. 애플리케이션에서 DELETE 순서만 맞추면
-- 동시 요청이 끼어든 순간 고아 행이 생길 수 있으므로, 여기서부터는 부모 삭제와 자식 생성을
-- PostgreSQL이 직렬화한다. 기존 고아 데이터가 있다면 마이그레이션을 실패시키는 것이 맞다.
-- 조용히 제약을 건너뛰면 환경마다 삭제 결과가 달라진다.

ALTER TABLE galleries
    ADD CONSTRAINT fk_galleries_studio
        FOREIGN KEY (studio_id) REFERENCES studios (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE gallery_members
    ADD CONSTRAINT fk_gallery_members_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE gallery_invites
    ADD CONSTRAINT fk_gallery_invites_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE photos
    ADD CONSTRAINT fk_photos_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE NOT VALID;

-- 발급된 PUT URL은 DB 삭제 뒤에도 만료 전까지 같은 키를 다시 쓸 수 있다. 새 서버는 SDK가
-- 돌려준 실제 서명 만료 시각을 명시적으로 저장한다. DEFAULT는 배포 전 기존 행과 rolling
-- 중 이 컬럼을 모르는 구버전 INSERT를 현재 설정 TTL 30분 동안 보수적으로 막는 cutover guard다.
-- URL을 발급하지 않는 공유 샘플 writer는 이 컬럼에 NULL을 명시적으로 넣는다.
ALTER TABLE photos
    ADD COLUMN upload_url_expires_at TIMESTAMP(6) WITH TIME ZONE
        DEFAULT (CURRENT_TIMESTAMP + INTERVAL '30 minutes');

ALTER TABLE photo_folders
    ADD CONSTRAINT fk_photo_folders_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE photo_folder_items
    ADD CONSTRAINT fk_photo_folder_items_folder
        FOREIGN KEY (folder_id) REFERENCES photo_folders (id) ON DELETE CASCADE NOT VALID,
    ADD CONSTRAINT fk_photo_folder_items_photo
        FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE photo_selections
    ADD CONSTRAINT fk_photo_selections_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE photo_selection_items
    ADD CONSTRAINT fk_photo_selection_items_selection
        FOREIGN KEY (selection_id) REFERENCES photo_selections (id) ON DELETE CASCADE NOT VALID,
    ADD CONSTRAINT fk_photo_selection_items_photo
        FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE photo_ratings
    ADD CONSTRAINT fk_photo_ratings_photo
        FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE NOT VALID;

-- NOT VALID로 제약을 먼저 설치하면 새 쓰기는 즉시 보호한다. 기존 행 검증은 이 트랜잭션이
-- 커밋된 뒤 V10에서 수행해 ADD CONSTRAINT가 잡은 강한 잠금을 검증 시간까지 유지하지 않는다.

-- 삭제 대상은 사라져도 누가 어떤 확인값으로 실행했는지는 남아야 한다.
-- 삭제된 스튜디오와 FK를 맺지 않는 이유도 같다.
CREATE TABLE studio_deletion_audits
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id         UUID         NOT NULL,
    studio_id          BIGINT       NOT NULL,
    studio_user_id     BIGINT       NOT NULL,
    operator_user_id   BIGINT       NOT NULL,
    studio_gallery_url VARCHAR(255) NOT NULL,
    reason             VARCHAR(1000) NOT NULL,
    gallery_count      INTEGER      NOT NULL,
    photo_count        INTEGER      NOT NULL,
    object_count       INTEGER      NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE,
    updated_at         TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_studio_deletion_audits_request_id UNIQUE (request_id)
);

CREATE INDEX idx_studio_deletion_audits_studio_id
    ON studio_deletion_audits (studio_id);

CREATE INDEX idx_studio_deletion_audits_operator_user_id
    ON studio_deletion_audits (operator_user_id);

-- S3 호출 전에 커밋되는 실행 점유 행. 같은 request_id는 한 요청만 삽입할 수 있다.
-- S3 전 abort만 점유를 지우고, S3 시작 뒤 실패는 RETRYABLE로 유지해 같은 요청만
-- 새 token으로 재점유·재시도하게 한다.
CREATE TABLE studio_deletion_claims
(
    request_id          UUID          PRIMARY KEY,
    claim_token         UUID          NOT NULL,
    studio_id           BIGINT        NOT NULL,
    operator_user_id    BIGINT        NOT NULL,
    studio_gallery_url  VARCHAR(255)  NOT NULL,
    reason              VARCHAR(1000) NOT NULL,
    plan_version        INTEGER       NOT NULL DEFAULT 1,
    state               VARCHAR(20)   NOT NULL DEFAULT 'RUNNING',
    claimed_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT statement_timestamp(),
    state_changed_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT statement_timestamp(),
    CONSTRAINT ck_studio_deletion_claims_plan_version CHECK (plan_version > 0),
    CONSTRAINT ck_studio_deletion_claims_state CHECK (state IN ('RUNNING', 'RETRYABLE')),
    CONSTRAINT uk_studio_deletion_claims_studio_id UNIQUE (studio_id)
);
