-- 운영자 승인 뒤 스튜디오를 지울 때 하위 메타데이터가 남지 않도록 DB가 경계를 보장한다.
--
-- 기존 스키마에는 엔티티 간 외래키가 없었다. 애플리케이션에서 DELETE 순서만 맞추면
-- 동시 요청이 끼어든 순간 고아 행이 생길 수 있으므로, 여기서부터는 부모 삭제와 자식 생성을
-- PostgreSQL이 직렬화한다. 기존 고아 데이터가 있다면 마이그레이션을 실패시키는 것이 맞다.
-- 조용히 제약을 건너뛰면 환경마다 삭제 결과가 달라진다.

ALTER TABLE galleries
    ADD CONSTRAINT fk_galleries_studio
        FOREIGN KEY (studio_id) REFERENCES studios (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE gallery_members
    ADD CONSTRAINT fk_gallery_members_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE gallery_invites
    ADD CONSTRAINT fk_gallery_invites_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE photos
    ADD CONSTRAINT fk_photos_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE photo_folders
    ADD CONSTRAINT fk_photo_folders_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE photo_folder_items
    ADD CONSTRAINT fk_photo_folder_items_folder
        FOREIGN KEY (folder_id) REFERENCES photo_folders (id) ON DELETE CASCADE NOT VALID,
    ADD CONSTRAINT fk_photo_folder_items_photo
        FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE photo_selections
    ADD CONSTRAINT fk_photo_selections_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE photo_selection_items
    ADD CONSTRAINT fk_photo_selection_items_selection
        FOREIGN KEY (selection_id) REFERENCES photo_selections (id) ON DELETE CASCADE NOT VALID,
    ADD CONSTRAINT fk_photo_selection_items_photo
        FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE photo_ratings
    ADD CONSTRAINT fk_photo_ratings_photo
        FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE NOT VALID;

-- NOT VALID로 제약을 먼저 설치하면 새 쓰기는 즉시 보호하면서 기존 행 스캔 동안의 강한 잠금을
-- 짧게 끝낼 수 있다. 아래 검증은 고아 행이 하나라도 있으면 배포를 멈춘다.
ALTER TABLE galleries VALIDATE CONSTRAINT fk_galleries_studio;
ALTER TABLE gallery_members VALIDATE CONSTRAINT fk_gallery_members_gallery;
ALTER TABLE gallery_invites VALIDATE CONSTRAINT fk_gallery_invites_gallery;
ALTER TABLE photos VALIDATE CONSTRAINT fk_photos_gallery;
ALTER TABLE photo_folders VALIDATE CONSTRAINT fk_photo_folders_gallery;
ALTER TABLE photo_folder_items VALIDATE CONSTRAINT fk_photo_folder_items_folder;
ALTER TABLE photo_folder_items VALIDATE CONSTRAINT fk_photo_folder_items_photo;
ALTER TABLE photo_selections VALIDATE CONSTRAINT fk_photo_selections_gallery;
ALTER TABLE photo_selection_items VALIDATE CONSTRAINT fk_photo_selection_items_selection;
ALTER TABLE photo_selection_items VALIDATE CONSTRAINT fk_photo_selection_items_photo;
ALTER TABLE photo_ratings VALIDATE CONSTRAINT fk_photo_ratings_photo;

-- 삭제 대상은 사라져도 누가 어떤 확인값으로 실행했는지는 남아야 한다.
-- 삭제된 스튜디오와 FK를 맺지 않는 이유도 같다.
CREATE TABLE studio_deletion_audits
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id         UUID         NOT NULL,
    studio_id          BIGINT       NOT NULL,
    studio_user_id     BIGINT       NOT NULL,
    operator_user_id   BIGINT       NOT NULL,
    studio_gallery_url VARCHAR(255) NOT NULL,
    reason             VARCHAR(1000) NOT NULL,
    gallery_count      INTEGER      NOT NULL,
    photo_count        INTEGER      NOT NULL,
    object_count       INTEGER      NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE,
    updated_at         TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_studio_deletion_audits_request_id UNIQUE (request_id)
);

CREATE INDEX idx_studio_deletion_audits_studio_id
    ON studio_deletion_audits (studio_id);

CREATE INDEX idx_studio_deletion_audits_operator_user_id
    ON studio_deletion_audits (operator_user_id);
